// ==UserScript==
// @name         NovelAI 简体中文全局汉化
// @namespace    https://github.com/TataraMo/NovelAI-Localization-zh_CN
// @version      4.6.0
// @description  NovelAI Full Site Localization into Simplified Chinese
// @author       W是包子N不理, Optimized by Assistant
// @match        https://novelai.net/*
// @icon         https://novelai.net/icons/novelai-round.png
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_registerMenuCommand
// @downloadURL  https://update.greasyfork.org/scripts/571008/NovelAI%20%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E5%85%A8%E5%B1%80%E6%B1%89%E5%8C%96.user.js
// @updateURL    https://update.greasyfork.org/scripts/571008/NovelAI%20%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E5%85%A8%E5%B1%80%E6%B1%89%E5%8C%96.meta.js
// @license      GPL-3.0-or-later
// ==/UserScript==

(function() {
    'use strict';

    // ==========================================
    // 1. 设置与开关管理
    // ==========================================
    const config = {
        enable: GM_getValue('enable_translation', true)
    };

    GM_registerMenuCommand(`[${config.enable ? '√' : '×'}] 全局汉化开关`, () => {
        GM_setValue('enable_translation', !config.enable);
        location.reload();
    });

    if (!config.enable) return;

    // ==========================================
    // 2. 通用词库
    // ==========================================
    const i18n = {
        // --- 登录与注册 ---
        'You must enter your password to access your': '您必须输入密码才能访问您的',
        'You must enter your password to access your stories.': '请输入密码以访问您的故事库。',
        'Create an account and start for free': '注册账号，即刻免费体验',
        'Sign Up': '注册账号',
        'Log In': '登 录',
        'stories.': '故事。',
        'this.': '这部分。',
        'Submit': '提 交',
        'SUBMIT': '提 交',
        'submit': '提 交',
        'Enter your password': '请输入您的密码',
        'Password Required': '需要验证密码',
        'Forgot Password': '忘记密码',
        'Update': '更 新',
        'Error unlocking keystore: Incorrect password.': '解锁失败：密码不正确。',
        'Welcome back!': '欢迎回来！',
        'Remember me': '保持登录',
        'Login is remembered for 30 days': '登录状态将保持 30 天',
        'Sign In': '登 录',
        'Back': '返 回',
        'Reset Password': '重置密码',
        'Repeat Password': '确认密码',
        'Would you like to receive emails about updates from us in the future?': '您是否愿意在未来接收我们的更新资讯邮件？',
        'By submitting this form, you will receive an email containing a password reset link with further steps.': '提交后，您将收到一封包含密码重置链接与后续步骤的邮件。',
        'Due to local encryption, resetting your password results in permanently losing access to your remotely stored stories and AI Modules.': '由于采用本地加密技术，重置密码会导致您永远失去对云端故事和 AI 模块的访问权限。',
        'Start Creating!': '开始创作！',

        // --- 公告与动态 ---
        'Image Generation Canvas Update: New Tools, Better Performance, and 3D Support': '画板更新：全新工具、性能提升及 3D 支持',
        'Precise Reference Release: Character & Style References + Reference Inpainting': '精准参考功能上线：角色与画风参考 + 参考重绘',
        'Introducing NovelAI User Scripts': 'NovelAI 用户脚本系统上线',
        'NovelAI\'s scripting system is here! Providing deep functionality, custom UI components, generation hooks, and document modification.': 'NovelAI 的脚本系统正式上线！为您提供底层功能接入、自定义界面组件、生成拦截器以及文档修改能力。',

        // --- 侧边栏与设置 ---
        'User Settings': '用户设置',
        'AI Settings': 'AI 设置',
        'Interface': '界面与外观',
        'Theme': '主题配色',
        'Account': '账户管理',
        'Old Email': '原电子邮箱',
        'New Email': '新电子邮箱',
        'Current Email': '当前电子邮箱',
        'Current Password': '当前密码',
        'New Password': '新密码',
        'Confirm New Password': '确认新密码',
        'Your Stories': '您的故事',
        'Search your stories': '搜索故事...',
        'Filters': '过滤与筛选',
        'Display': '显示方式',
        'Compact View': '紧凑模式',
        'Show On Top': '置顶显示',
        'Shelves': '书架',
        'Favorites': '我的收藏',
        'Local Stories': '本地故事',
        'Sort By': '排序方式',
        'Most Recent': '最近编辑',
        'Alphabetical': '名称排序',
        'Creation Date': '创建日期',
        'New Shelf': '新建书架',
        'Import File': '导入文件',
        'Text To Speech': '文字转语音 (TTS)',
        'Defaults': '默认偏好',
        'Support': '帮助与支持',
        'Change Log': '更新日志',
        'Hotkeys': '快捷键大全',
        'Logout': '退出登录',
        'Your subscription renews around': '您的订阅将在该日期前后续费:',
        'Not possible while subscribed.': '订阅期间无法执行此操作。',

        // --- AI 响应设置 ---
        'AI Responses': 'AI 响应设置',
        'Stream AI Responses': '流式生成文本',
        'AI responses will be streamed, appearing token by token.': 'AI 生成的内容将像打字机一样逐字显示。',
        'Text will appear all at once when generation has finished.': '生成完成后，文本会一次性完整呈现。',
        'Continue Response to End of Sentence': '自动补全至句末',
        'Responses will attempt to continue until the end of a sentence is found.': 'AI 响应会尝试一直生成，直到识别出一个完整的句号。',
        'Responses will end normally.': '达到最大字数限制后直接中断生成。',
        'Streamed Response Delay': '流式输出延迟',
        'Default: 0': '默认值：0',

        // --- 评论输出 ---
        'Hypebot': '互动机器人',
        'Comment Output': '互动频次',
        'Off': '关闭',
        'Automatic': '自动',
        'Permanent': '常驻',
        'Clear Comments': '清空评论',
        'Automatically clear comments on generating story text.': '生成新故事时自动清除之前的评论。',
        'Don\'t automatically clear comments on generating story text.': '生成新故事时保留之前的评论。',
        'Comment Chance': '触发概率',
        'Default: 5%': '默认值：5%',
        'Comment Avatar': '机器人头像',
        'Auto-Select': '自动分配',
        'Comment Streamed Response Delay': '评论流式输出延迟',

        // --- 实验性与高级 ---
        'Experimental': '实验性功能',
        'Preamble': '预设前言',
        'The context will have a small preamble prepended to improve generations on low context. The exact behaviour varies per model.': '在上下文顶部注入一段隐藏的预设前言，以改善字数较少时的生成质量。具体效果因模型而异。',
        'The context will not have a preamble prepended.': '上下文顶部不会注入任何前言。',
        'Default Bias': '默认规避',
        'A default bias will be applied, reducing the likelyhood of dinkus (***) and asterism (⁂) to be generated.': '启用后将自动抑制章节分隔符 (***) 与星群符号 (⁂) 的生成频率。',
        'No default bias will be applied.': '不对特殊符号施加默认抑制。',
        'Enable Token Probabilities': '开启词元概率查看',
        'Generation requests will return token probabilities for the response which can be examined by clicking the': '生成完毕后将返回候选词元的概率分布，您可以点击',
        'button next to Retry.': '“重试”按钮旁的图标进行查看。',
        'Token probabilities will not be returned with generation requests.': '禁用词元概率分析功能。',
        'Editor Token Probabilities': '编辑器内显概率',
        'Selectable alternate tokens and probabilities will be shown in the editor.': '在编辑器内直接显示可选的备用词汇及其概率。',
        'Enable to show selectable alternate tokens and probabilities in the editor.': '开启后可在编辑器内直接查看并选择备用的生成词汇。',

        // --- 界面与外观 ---
        'UI Language': '界面语言',
        'English': '英文',
        'Text Settings': '文本排版',
        'Interface Font Size': '界面字号',
        'px': '像素',
        'Default: 16px': '默认：16px',
        'Line Spacing': '行间距',
        'em': 'em',
        'Default: 1.8em': '默认：1.8em',
        'Paragraph Spacing': '段落间距',
        'Default: 0.5em': '默认：0.5em',
        'Max Line Width': '最大行宽',
        'Default: 100% (1200px)': '默认：100% (1200px)',
        'Output Font Size': '编辑器字号',
        'Default: 18px': '默认：18px',
        'Paragraph Indent': '首行缩进',
        'Default: 10px': '默认：10px',
        'Button Scale': '按钮缩放',
        'Default: 1': '默认：1',

        // --- 交互设置 ---
        'Interaction Settings': '交互与控制',
        'Gesture Controls': '触屏手势操作',
        'Swiping on touch devices will open and close the sidebars.': '在触摸屏设备上左右滑动可呼出或隐藏侧边栏。',
        'Gesture controls are disabled.': '触屏手势已被禁用。',
        'Swap Context Menu Controls': '反转右键菜单行为',
        'Right click will open the standard context menu. Ctrl+right click will open the NAI context menu.': '右键点击唤出浏览器原生菜单。Ctrl+右键 唤出 NovelAI 专属菜单。',
        'Right click will open the NAI context menu. Ctrl+right click will open the standard context menu.': '右键点击唤出 NovelAI 专属菜单。Ctrl+右键 唤出浏览器原生菜单。',

        // --- 编辑器与其他 ---
        'Other Settings': '其他偏好',
        'Input Box': '底部输入框',
        'The input box is visible.': '显示界面底部的指令输入框。',
        'The input box is hidden.': '隐藏底部指令输入框，保持界面极简。',
        'Editor Spellcheck': '编辑器拼写检查',
        'Spellcheck is enabled in the editor (on supported browsers)': '启用浏览器原生的拼写检查功能。',
        'Spellcheck is disabled in the editor.': '已关闭拼写检查。',
        'Editor Lorebook Keys': '高亮世界书关键词',
        'Keys of currently active Lorebook entries will be bolded in the editor. Disabling this setting may improve performance on very large stories or stories with large Lorebooks.': '当文中出现已激活的世界书关键词时会加粗显示。关闭此功能可提升长篇故事或巨型设定的编辑流畅度。',
        'No special styling will be applied to Lorebook keys in the editor.': '关键词不会在文中做任何特殊标记。',
        'Show Tips': '显示操作提示',
        'Tips will be shown below the editor.': '在编辑器下方滚动显示使用小贴士。',
        'Tips will not be shown.': '隐藏下方的小贴士。',
        'Auto Format Text': '文本自动排版',
        'Text—both user and generated—will be automatically formatted in the editor.': '自动对用户输入与 AI 生成的文本进行缩进和对齐排版。',
        'Text—both user and generated—will not be automatically formatted in the editor.': '不对文本进行任何强制排版。',
        'Editor Highlighting': '编辑器颜色标注',
        'Text in the editor will be highlighted based on origin.': '以不同颜色标注用户手写、AI生成及后期编辑的文本。',
        'Text in the editor will not be highlighted.': '文本统一颜色，不区分来源。',
        'Context Viewer Colors': '上下文颜色编码',
        'Text in the context viewer will be color coded based on origin.': '在“上下文查看器”中对不同来源的内容进行色彩编码。',
        'Text in the context viewer will use the default color.': '在“上下文查看器”中统一使用默认文字颜色。',
        'Show Story Title': '顶部显示标题',
        'Looks like your Library is empty.': '您的故事库似乎空空如也。',
        'Start your first Story': '开启您的第一个篇章',
        'The story title will be shown above the editor.': '在编辑器正上方展示当前故事标题。',
        'The story title will not be shown above the editor.': '隐藏编辑器顶部的故事标题。',
        'Show Editor Toolbar': '划词悬浮工具栏',
        'A toolbox with options to change text formatting and more will appear when selecting text in Editor V2.': '在 V2 编辑器中选中文本时，会自动弹出加粗、斜体等排版快捷工具箱。',
        'Selecting text in Editor V2 will not open the toolbox to change text formatting and more.': '选中文本时不再弹出悬浮工具箱。',
        'Keyboard Displaces Content': '移动端键盘行为适配',
        'The onscreen keyboard of some mobile devices will displace the content of the page.': '当唤出虚拟键盘时，自动将整个页面内容向上推起。',
        'The onscreen keyboard of some mobile devices will overlay the content of the page.': '虚拟键盘将直接覆盖在页面之上。',
        'Paragraph Visibility Range': '视口渲染范围优化',
        'Paragraphs scrolled out-of-view past the set range will be unloaded in Editor V2. This improves editing performance especially with larger stories.': '滚动出设定范围的段落将被暂时卸载，以大幅提升超长篇故事的渲染性能。',
        'Default: 1000': '默认值：1000',
        'Highlight Speech': '突出显示人物对话',
        'Choose if speech (text between quotation marks) in the editor should be highlighted in italic and slightly less opaque. When choosing Inverted, non-speech is shown in italic and slightly less opaque instead.': '选择是否将引号内的对白呈现为微透斜体。如果选择“反转”，则对旁白进行斜体和透明处理，让对白更加醒目。',
        'Only available in Editor V2.': '此功能仅限 V2 版编辑器使用。',
        'Highlight': '对白淡化',
        'Inverted': '旁白淡化 (反转)',
        'Show Identicon': '使用哈希头像',
        'A unique identicon will be shown for your account.': '为您的账号生成并显示一枚独特的像素哈希头像。',
        'A theme-specific default avatar will be shown for your account.': '显示一套随主题配色的默认头像。',
        'Show Minibar (Desktop Only)': '显示左侧迷你栏',
        'The minibar will display on the left side of the screen.': '在桌面端屏幕最左侧常驻显示迷你快捷栏。',
        'The minibar will not be displayed.': '隐藏最左侧的迷你快捷栏。',

        // --- 主题 ---
        'Apply & Save Theme': '保存并应用主题',
        'Import': '导入',
        'Export': '导出',
        'Default Themes': '预设主题',
        'NovelAI Dark': 'NovelAI 经典暗黑',
        'NovelAI Light': 'NovelAI 简约亮色',
        'Slate': '深空石板',
        'Midnight Doll': '午夜人偶',
        'Subtle Terminal': '复古终端',
        'Bubblegum': '粉彩泡泡糖',
        'Matrix': '黑客帝国',
        'Purple Noir': '紫夜迷雾',
        'Sagiri': '纱雾 (和风)',
        'Monkey': '猿猴',
        'Ink': '水墨',
        'Wine': '红酒',
        'Vibrowave': '蒸汽波 (赛博)',
        'Sand': '流沙',
        'Gruvbox Dark': 'Gruvbox 护眼暗色',
        'Counter Militant': '反击武装',
        'Amber': '复古琥珀',
        'Frog': '青蛙',
        'NovelAI Dark (Legacy)': 'NovelAI 经典暗黑 (旧版)',
        'Theme Editor': '主题定制器',
        'This is paragraph text. Nice!': '这是一段普通文本。很不错吧！',
        'This is a prompt.': '这是一段用于引导 AI 的提示词。',
        'This is AI text.': '这是由 AI 生成出来的文本。',
        'This is edited text.': '这是您手动修改过的文本。',
        'This is new user text.': '这是您新写入的文本内容。',
        'This is highlighted text.': '这是被高亮标记的内容。',
        'Header Font': '标题字体',
        'Paragraph Font': '正文字体',
        'Header': '标题配色',
        'Paragraph': '正文配色',
        'Warning/Error': '警告/报错配色',
        'Foreground': '前景色 (文字等)',
        'Background': '主背景色',
        'Dark Background': '深色区域背景',
        'Input Background': '输入框背景',
        'Low Intensity Color': '低饱和度辅色',
        'Mid Intensity Color': '中等饱和度辅色',
        'High Intensity Color': '高饱和度点缀色',
        'Custom CSS': '自定义 CSS 代码',

        // --- 账户管理 ---
        'Current Tier': '当前订阅方案',
        'Not Subscribed': '暂未订阅',
        'Manage': '管理订阅',
        'Pen Name': '作者昵称',
        'Change': '修 改',
        'Delete Account': '注销账户',
        'Request': '申请操作',
        'Password': '账户密码',
        'Change Password': '修改密码',
        'Show Account ID': '查看账户 ID',
        'Get Persistent API Token': '获取永久 API 令牌',
        'Stay Informed.': '掌握最新资讯。',
        'Subscribe to our newsletter.': '订阅我们的新闻周刊。',
        'Subscribe': '立即订阅',
        'You’re signed up to our newsletter.': '您已成功订阅新闻周刊。',
        'You’ll receive emails from us when we release new updates and other news.': '当有重磅更新或新闻时，我们将第一时间通过邮件通知您。',
        'Unsubscribe': '取消订阅',
        'Manage Cookie Preferences': 'Cookie 隐私偏好',
        'Default Storage Location': '默认存储位置',
        'Local': '本地缓存',
        'Server': '云端服务器',
        'New & imported stories will be saved locally and stored encrypted remotely.': '新建与导入的故事将缓存于本地，并同步加密存储至云端。',
        'New & imported stories will be saved locally only.': '您的故事将仅保存在本设备浏览器中。',
        'Exporting and backing up your stories is highly recommended, should your browser cache get cleared, or if you lose access to your account.': '强烈建议您定期导出备份，以防清理浏览器缓存或遗失账户导致数据丢失！',
        'Download All Stories': '打包下载全部故事',
        'Gift Key (Purchasing Disabled)': '兑换密钥 (已暂停发售)',
        'Gift key purchases have been removed indefinitely due to abuse.': '由于被恶意滥用，购买兑换密钥的功能已被无限期下线。',
        'Purchase New Gift Key': '购买新的兑换密钥',
        'Key': '兑换码',
        'Date Created': '创建日期',
        'Tier': '包含的套餐',
        'Status': '使用状态',
        'No Gift Keys yet!': '您还没有任何兑换密钥！',
        'Enter your email address below to receive an account deletion confirmation email.': '在下方填入注册邮箱，我们将向您发送一封注销确认邮件。',
        'Be aware that the deletion of your account results in the permanent loss of your stories and other content!': '警告：注销账户将导致您的故事与所有生成数据永久毁灭！',
        'Email': '电子邮箱',
        'Send Deletion Confirmation Email': '发送注销确认邮件',
        'To change your password, please enter your current password and then your new password.': '修改密码前，请先验证当前登录的密码。',
        'Custom CSS is experimental and some changes could cause the UI to become unusable. Future updates could change the default styles and make custom CSS set here not function as intended. Alt + Shift + P can be used to reset your theme to the default theme.': '自定义 CSS 属于高阶功能，编写不当可能导致界面崩溃。按 Alt+Shift+P 快捷键可随时强行重置为默认主题。',
        'Cancel': '取 消',
        'Save': '保 存',

        // --- 语音设置 (TTS) ---
        'Text to Speech Source': '发音合成来源',
        'Local TTS uses your browsers available speech synthesis capabilities.': '本地合成：调用您系统及浏览器自带的语音合成引擎（完全免费）。',
        'Streamed TTS is higher quality, uses a model hosted by NovelAI, and requires an active subscription. 100 free generations given for trial purposes.': '云端流式：采用 NovelAI 自研的顶级拟真发音模型，需保持订阅。免费账户提供 100 次试听额度。',
        'Your browser does not support local TTS.': '您当前的浏览器环境不支持本地语音合成。',
        'Streamed': '云端流式',
        'TTS will use NovelAI\'s remote TTS service.': '将使用 NovelAI 官方的高品质语音云服务。',
        'Speak Outputs': '朗读 AI 续写',
        'Outputs will be read by TTS.': 'AI 每次生成的内容都将被自动朗读出来。',
        'Outputs will not be read.': '静默模式，仅文字显示 AI 内容。',
        'Speak Inputs': '朗读用户输入',
        'In addition to outputs, Inputs will be read by TTS.': '除了 AI 生成的文字，您亲手敲下的内容也会被一并朗读。',
        'Has no effect if speak outputs is disabled': '需先开启“朗读 AI 续写”该项才能生效',
        'Inputs will not be read.': '您输入的文字将不会被朗读。',
        'Speak HypeBot Comments': '朗读互动机器人',
        'HypeBot comments will be read by TTS.': '互动机器人吐槽的内容也会被赋予声音。',
        'HypeBot comments will not be read.': '让互动机器人安安静静地打字吐槽就好。',
        'Streamed TTS Settings': '云端语音参数',
        'Model': '声音模型',
        'Story Voice': '旁白声音',
        'Text entered here will be used for the test/download buttons.': '在此输入的文本将用于底部的测试朗读。',
        'Saved Voices': '我保存的音色',
        'Select a voice to edit': '选择一个音色进行微调',
        'Name': '音色名称',
        'Seed': '声纹种子',
        'Randomize': '随机捏脸',
        'Save Voice': '收藏音色',
        'Delete Voice': '删除音色',
        'Volume': '播放音量',
        'Speed': '语速调节',
        'Note: Will not affect the speed of downloaded audio.': '注：这只改变当前播放速度，不影响您下载的音频文件原速。',
        'HypeBot Voice': '机器人的声音',
        'unisex': '中性',
        'female': '女声',
        'male': '男声',
        'No saved voices. Add one first.': '您还没有保存过任何音色。先去调教一个吧。',
        'Voice': '系统自带音色',
        'unknown voice': '未知声线',
        'custom': '自制声纹',
        'Seed Input': '声纹种子输入',
        'TTS will use the browsers Speech Synthesis API.': '将直接调用浏览器的 Web Speech API 发声。',
        'Local TTS Settings': '本地发声参数',
        'Google US English': 'Google 美国英语 (女)',
        'Test Voice': '测试朗读',
        'Pitch': '音调高低',
        'Microsoft Huihui - Chinese (Simplified, PRC)': '微软慧慧 - 中文',
        'Language: zh-CN, Local: Yes': '语言: 简体中文, 类型: 本地引擎',

        // --- AI 预设管理 ---
        'Default AI Model': '默认 AI 写作模型',
        'New stories will use this model by default.': '每次新建故事时，默认唤醒这位 AI 大脑。',
        'A massive and versatile 355B Mixture of Experts model.': '包含 3550 亿参数的超大规模混合专家 (MoE) 模型。',
        'Default Preset': '默认生成偏好',
        'New Stories will use the selected preset as a default.': '新故事会默认应用您选中的这套文本随机性配置。',
        'Default AI Module': '默认微调模块',
        'The selected AI Model does not support Modules.': '当前所选的 AI 模型无法挂载外部微调模块。',
        'Lorebook Generation Settings': '世界书生成参数',
        'Change the Model and settings preset used by the Lorebook Generator.': '独立配置在自动补全“世界书设定”时专用的 AI 模型与偏好。',
        'Lorebook Generation Model': '指定创作模型',
        'Lore Generation Preset': '指定文本偏好',
        'Legacy Lore Generation': '使用旧版生成逻辑',

        // --- 编辑器顶部/底部菜单 ---
        'Toggle Menu Bar': '展开/收起 左侧库',
        'Toggle Info Bar': '展开/收起 右侧参数',
        'Toggle Bars': '切换全屏沉浸模式',
        'Focus Editor': '光标回到编辑器',
        'Request AI Generation': '命令 AI 开始续写',
        'Generate Inline': '内联插入生成',
        'Cancel AI Generation': '中断 AI 生成',
        'Focus Input Field': '聚焦底部输入框',
        'Redo': '重做 (前进)',
        'Open Redo List': '挑选重做的分支',
        'Undo': '撤销 (后退)',
        'Retry AI Generation': '重新掷骰生成',
        'Open Lorebook': '翻开世界书设定集',
        'Open Context Viewer': '审视后台上下文',
        'Open User Scripts Modal': '用户脚本管理',
        'Open Tokenizer': '词元(Token)切割器',
        'Open Token Probabilities': '查看词汇概率',
        'Toggle Editor Token Probabilities': '开关编辑器内概率',
        'Close Modal': '关闭弹窗',
        'Toggle Input Box': '显示/隐藏 底部输入框',
        'Toggle Highlighting': '切换颜色标注',
        'Toggle Spellcheck': '切换拼写检查',
        'Create New Story': '新建空白故事',
        'Reset Theme': '重置主题配色',
        'Delete Current Story': '销毁当前故事',
        'Stop TTS': '停止语音播报',
        'Toggle Bold': '加粗标记',
        'Toggle Italic': '斜体标记',
        'Toggle Underline': '下划线',
        'Toggle Strikethrough': '删除线',
        'Remote Storage': '云端同步状态',
        'Switch to Remote Storage': '迁移故事至云端',
        'Keep Local Storage': '仅保留在本地',
        'Author': '当前作者',
        'Account Settings': '账户详情设置',
        'Other': '其他工具',
        'Image Generation': '前往图像生成',
        'Tokenizer': '词元测试器',
        'User Scripts': '用户定制脚本',
        'Help': '寻求帮助',
        'Tutorial': '新手引导',
        'Documentation': '官方详尽文档',
        'Version': '网页版本',
        'Enter Password': '验证您的密码',
        'Dashboard': '回到首页大厅',
        'Manage Account': '账户管理面板',
        'Latest News': '官方最新资讯',
        'Read More': '阅读完整内容',
        'Welcome back, Author': '好久不见，大作家',

        // --- 主页/引导 ---
        'Continue a Story': '接续未完的篇章',
        'Visualize your favorite characters.': '将你脑海中的挚爱角色化为视觉盛宴。',
        'Image Generator': '画板中心',
        'Generate Anime and Furry imagery with our SOTA image gen model!': '使用我们业界领先的图像生成模型，创作动漫与兽人插画！',
        'Director Tools': '高级编辑工具',
        'Use a variety of AI tools to edit your images.': '使用强大的 AI 图像工具对画作进行后期处理。',
        'New Story': '创建新故事',
        'Image Gen': '图像生成',
        'There are issues connecting to the backend right now, please check your connection or try again...': '目前连接核心服务器遇到阻碍，请检查您的网络节点或稍后重试...',
        'Free Trial': '免费畅玩',
        'You\'re getting': '您目前拥有',
        'tokens of AI context. Equivalent to our': '词元的 AI 上下文记忆。性能等同于我们的',
        'Scroll tier': 'Scroll 套餐级别',
        'Seen enough?': '想要更深度的体验？',
        'Check out our plans': '浏览高级订阅方案',
        'We value your privacy and security. Your stories, settings presets, and other remotely stored content is encrypted locally on your computer. In order to decrypt your content and maintain your privacy you must enter the password you set previously.': '我们极度重视隐私。您的所有数据均在本地加密后再上传。为了解锁并读取您的私人故事，必须提供解密密码。',
        'Before your text is sent to the AI, it gets turned into numbers in a process called tokenization.': '在发送给 AI 处理前，您的文本会经过“分词”处理并转化为数字序列。',
        'These tokens are how the AI reads and interprets text.': 'AI 正是通过这些“词元”来读取和理解文本内容的。',
        'The average token is around 4 characters long, but many common words are their own token.': '平均一个词元大约包含 4 个字符，不过许多常见词汇本身就独占一个词元。',
        'The tokenizer for your currently selected model is the GLM Tokenizer.': '您当前所选模型使用的核心分词器为 GLM Tokenizer。',
        'Text Input': '输入文本测试',
        'ID Input': '输入 ID 测试',
        'Stories - NovelAI': '故事控制台 - NovelAI',
        'Opus Tier': 'Opus (幻之章) 套餐',
        'Scroll Tier': 'Scroll (卷轴) 套餐',
        'Tablet Tier': 'Tablet (石板) 套餐',
        'Interactive Tutorials': '沉浸式互动教程',
        'NovelAI Discord': '加入 Discord 社区',
        'a few seconds ago': '几秒前',
        '4 minutes ago': '4 分钟前',
        'a day ago': '1 天前',
        'Last Edited: a few seconds ago': '最后动笔：几秒前',
        'Last Edited: 4 minutes ago': '最后动笔：4 分钟前',
        'Last Edited: a day ago': '最后动笔：1 天前',
        'Let\'s start writing!': '挥洒创意，即刻开始！',
        'Select an option to continue.': '请选择一个方向启程。',

        // --- 图像生成专属 ---
        'Anlas:': '代币余额:',
        'Quick Start Gallery': '灵感画廊',
        'Text Generation': '返回文字模式',
        'NAI Diffusion V4.5 Curated': 'NAI Diffusion V4.5 严选优享版',
        'A version of our newest model trained on a curated subset of images. Recommended for streaming.': '基于极致筛选的数据集训练的最新模型，画面更加纯粹，极力推荐！',
        'Base Prompt': '全局基础提示词',
        'Undesired Content': '反向提示词 (不想要的)',
        'Prompt': '提示词',
        'or': '或',
        'Quality Tags Enabled': '已附加画质提升标签',
        'Add a Base Img (Optional)': '垫入基础底图 (图生图)',
        'Character Prompts': '角色专用提示词',
        'Customize separate characters.': '独立定制画面中每个角色的外观。',
        'Add Character': '增加一名角色',
        'Vibe Transfer': '风格提取 (参考图)',
        'Change the image, keep the vision.': '重塑画面，保留神韵。',
        'Precise Reference': '精准参考 (人物/画风)',
        'Add a reference image for a character or style.': '精准锚定特定角色的面容，或整张图的笔触风格。',
        'Image Settings': '生成参数面板',
        'Normal Portrait': '标准肖像',
        'Steps': '迭代步数',
        'Guidance': '服从度 (CFG)',
        'Seed': '随机种子',
        'N/A': '无限制',
        'Sampler': '采样算法',
        'Euler Ancestral': 'Euler Ancestral (祖先欧拉)',
        'Generate 1 Image': '消耗代币生成 1 张',
        'Anlas': '代币',
        'Get Started': '新手启航',
        'Get Inspiration from our quick start gallery!': '缺乏灵感？从画廊中抄个作业吧！',
        'Click an image to copy the prompt.': '点击下方任意美图即可窃取其提示词。',
        'Copied!': '提示词已入袋！',
        'History': '历史印记',
        'Download Image': '保存到本地',
        'Copy to Clipboard': '复制图像内容',
        'Pin Image': '将此图钉在右侧',
        'Download ZIP': '打包下载为 ZIP',
        'Clear History': '清空本次生成记录',
        'Enhance': '细节提升',
        'Generate Variations': '基于此图生成变体',
        'Upscale': '无损超分辨率放大',
        'Use as Base Image': '将其设为底图',
        'Edit Image': '进入编辑工坊',
        'Draw an outline of your image.': '提取当前图像的黑白轮廓线条。',
        'Revert your image to a sketch stage.': '剥离色彩与细节，将其还原为早期草图。',
        'Turn your sketch or line art picture into something colorful. You can also guide your colorization with a prompt and even make slight modifications to the image.': '为草图或线稿注入灵魂色彩。您还可使用提示词来指定色彩偏好。',
        'Remove backgrounds from images, leaving only the characters.': '一键智能抠图，彻底剔除背景。',
        'Change the expression of any given character.': '施展魔法，随心改变角色的面部表情。',
        'Removes clutter like text, speech bubbles or other things drawn on top of the image.': '清理画面中的违和文字、对话气泡等一切煞风景的杂物。',
        'What do you want to do with this image?': '您打算对这件艺术品做些什么？',
        'Image2Image': '图生图向导',
        'Defry': '画质修复 (去噪)',
        'Prompt (Optional)': '输入意图 (选填)',
        'Happy': '喜笑颜开',
        'Sad': '黯然神伤',
        'Angry': '怒火中烧',
        'Scared': '惊恐万状',
        'Surprised': '大惊失色',
        'Tired': '疲倦不堪',
        'Excited': '兴奋雀跃',
        'Nervous': '局促不安',
        'Thinking': '陷入沉思',
        'Confused': '满脸困惑',
        'Shy': '羞涩红晕',
        'Disgusted': '嫌弃作呕',
        'Smug': '得意洋洋',
        'Bored': '百无聊赖',
        'Laughing': '捧腹大笑',
        'Irritated': '烦躁气恼',
        'Aroused': '情色欲动',
        'Embarrassed': '社死尴尬',
        'Worried': '忧心忡忡',
        'Love': '爱意绵绵',
        'Determined': '目光坚定',
        'Hurt': '受伤苦楚',
        'Playful': '俏皮吐舌',
        'Anime Only. Start with a neutral emotion image.': '注：仅支持动漫模型。请尽量提供一张无表情的底图以获得最佳效果。',
        'Learn More': '探索操作手册',
        'Neutral': '面无表情',
        'Transform your image.': '对图像进行多维度转换。',
        'Enhance Image': '细节提升面板',
        'Enhance!': '开始增强！',
        'Upscale Amount': '画面放大倍率',
        'Magnitude': '重绘强度',
        'Show Advanced': '展开高级选项',
        'Strength': '重绘幅度',
        'Noise': '引入噪声',
        'Strength:': '幅度:',
        'Noise:': '噪声:',
        'Draw Mask': '绘制蒙版',
        'Erase Mask': '擦除蒙版',
        'Focused': '聚焦模式',
        'Area': '区域圈选',
        'Selection': '自由选择',
        'Square Brush': '方形笔刷',
        'Hide Advanced': '收起高级选项',
        'Remove BG': '一键抠图',
        'Minimum Context Area:': '最小参照范围:',
        'Mask Color': '蒙版染色',
        'Mask Opacity:': '蒙版不透明度:',
        'Border': '边缘溢出',
        'Mask Pattern': '蒙版花纹',
        'Reference Strength': '参考权重',
        'Information Extracted': '特征提取深度',
        'Fidelity:': '保真度:',
        'Enabled': '已生效',
        'Character & Style': '角色与画风混合',
        'Character': '仅限角色外貌',
        'Style': '仅限整体画风',
        'Erase': '橡皮擦',
        'Fill': '油漆桶',
        'Select': '框选',
        'Lasso': '套索',
        'Color Picker': '吸管取色',
        'Blur': '边缘模糊',
        'Clone': '印章克隆',
        'Position': '人物站位',
        'AI’s Choice': '交由 AI 定夺',
        'Slightly Weak': '轻微干预',
        'Weak': '低权重',
        'Even Weaker': '微乎其微',
        'Very Weak': '极低权重',
        'Weakest': '忽略不计',
        'Normalize Reference Strength Values': '平滑参考权重曲线',
        'Learn more here.': '点此查阅进阶指南。',
        'This image has metadata!': '检测到该图内嵌了生成参数！',
        'Did you want to import that instead?': '您是否需要一键提取并应用这些参数？',
        'Append': '追加到当前提示词',
        'Import Metadata': '覆盖导入所有参数',
        'Click to edit a character.': '点我配置角色的详细特征。',
        'Done': '确认无误',
        'Character Positions (Global)': '角色全局站位图',
        'Adjust': '微 调',
        'Clean Imports': '清理画布后导入',
        'Line Art': '提取线稿',
        'Sketch': '提取草图',
        'Colorize': '线稿上色',
        'Emotion': '修改表情',
        'Declutter': '画面清理',
        'Transform': '执行转换',
        'Send to Director Tools': '送入高级编辑工坊',
        'Inpaint Image': '局部重绘 (涂抹修改)',
        'New': '推荐',
        'NAI Diffusion V4.5 Full': 'NAI Diffusion V4.5 完整全量版',
        'Our newest and best model.': '无删减的知识库，细节更丰富，目前地表最强模型。',
        'Legacy': '已淘汰',
        'NAI Diffusion V4 Curated': 'NAI V4 严选优享版',
        'Our V4 model trained on a curated subset of images. No longer recommended for use.': '老旧模型，已被 V4.5 取代，不再推荐。',
        'NAI Diffusion V4 Full': 'NAI V4 完整全量版',
        'Our V4 model. No longer recommended for use.': '老旧全量模型。不再推荐。',
        'NAI Diffusion Anime V3': 'NAI 动漫 V3 经典版',
        'Our previous model. No longer recommended for use.': '曾经的王者，但已成时代的眼泪。',
        'NAI Diffusion Furry V3': 'NAI 兽人专用 V3',
        'Free': '免费白嫖',
        'Added to the end of the prompt:': '系统已在您的提示词末尾静默追加：',
        ', no text, best quality, very aesthetic, absurdres': ', 无文本, 画质巅峰, 极致美学, 荒诞级分辨率',
        'You are currently using Anime mode.': '您当前处于二次元动漫模式。',
        'The mode changes the tag suggestions and adds a dataset tag to the prompt. You can click the icon to switch.': '该模式会智能推荐动漫标签并注入专用水印。点击右侧图标可随时切换体系。',
        'You are currently using Furry mode.': '您当前处于福瑞 (兽人) 模式。',
        'Detach Undesired Content': '将反向提示词分离为独立输入框',
        'UC Preset Enabled': '已附加官方反向毒图预设',
        ', very aesthetic, masterpiece, no text, -0.8::feet::, rating:general': ', 极致美学, 传世杰作, 无文本, -0.8::feet::, 全年龄分级',
        'Prompt Settings': '提示词高阶玩法',
        'Reattach Undesired Content': '将反向提示词合并回主输入框',
        'Prompt Chunks': '提示词模块积木',
        'You': '你',
        'must': '必须',
        'enter': '输入',
        'your': '你的',
        'password': '密码',
        'to': '来',
        'access': '访问',
        'Add Quality Tags': '自动注入画质提升词',
        'Tags to increase quality will be prepended to the prompt.': '神级画质标签将会自动插入您的提示词头部。',
        'The prompt will be used unmodified.': '完全信任您的直觉，一字不改地原样生成。',
        'Undesired Content Preset': '反向毒图预设等级',
        'Heavy': '重度防御 (推荐)',
        'Disable Tag Suggestions': '关闭输入时弹出的标签联想',
        'Highlight Emphasis': '以颜色深浅显示权重分配',
        'Light': '轻度防御',
        'Human Focus': '侧重人体结构',
        'None': '全裸奔 (不加反向词)',
        'No custom prompt chunks yet. Click + to add one.': '您还没有积木块。点击 + 号把常用的长串提示词封装起来吧。',
        'Delete All': '清空所有积木',
        'Draw': '画笔',
        'Pen Size:': '笔刷粗细:',
        'Save & Close': '保存并退出',
        'Female': '女性角色',
        'Male': '男性角色',
        'Normal': '标准规格',
        'Portrait (832x1216)': '竖版 肖像照',
        'Landscape (1216x832)': '横版 风景照',
        'Square (1024x1024)': '1:1 正方形',
        'Large': '高规格',
        'Portrait (1024x1536)': '大图 竖版',
        'Landscape (1536x1024)': '大图 横版',
        'Square (1472x1472)': '大图 正方形',
        'Wallpaper': '壁纸规格',
        'Portrait (1088x1920)': '手机竖屏壁纸',
        'Landscape (1920x1088)': '电脑横屏壁纸',
        'Small': '低规格',
        'Portrait (512x768)': '小图 竖版',
        'Landscape (768x512)': '小图 横版',
        'Square (640x640)': '小图 正方形',
        'Custom': '随心所欲定制',
        'Number of Images': '一次性出图数量',
        'Steps:': '步数:',
        'Prompt Guidance:': '服从度:',
        'Variety+': '拓展多样性 (Variety+)',
        'Advanced Settings': '极客参数',
        'Prompt Guidance Rescale:': '服从度重缩放 (Rescale):',
        'Noise Schedule': '噪点退火策略',
        'Enable guidance only after body has been formed, to improve diversity and saturation of samples. May reduce relevance.': '仅在主体轮廓成型后才引入文字引导，可大幅提升画面多样性与色彩张力。代价是偶尔会跑题。',
        'Reset Settings': '恢复默认参数',
        'Reset all settings to default?': '确定要清除所有魔法参数，一键回退到默认状态吗？',
        'Yes': '狠心重置',
        'Recommended': '万金油 (推荐)',
        'karras (recommended)': 'karras 调度 (极力推荐)',
        'exponential': 'exponential (指数平滑)',
        'polyexponential': 'polyexponential (多项式指数)',
        'Added to the beginning of the UC:': '已静默注入反向提示词头部：',
        'blurry, lowres, upscaled, artistic error, film grain, scan artifacts, worst quality, bad quality, jpeg artifacts, very displeasing, chromatic aberration, halftone, multiple views, logo, too many watermarks, negative space, blank page': '糊成一团, 马赛克画质, 劣质拉伸, 透视崩坏, 满屏噪点, 扫描线, 史诗级烂图, 构图死板, jpg压缩包浆, 辣眼睛, 严重色散, 网点畸变, 多头多手, 水印糊脸, 负空间, 纯白纸一张',
        'Tolerance:': '容差范围:',
        'Intensity:': '作用强度:',
        'Alt+Click to set source': '按住 Alt 单击吸取色源',
        'HSV Adjustment': 'HSV 色彩学微调',
        'Hue:': '色相偏移:',
        'Saturation:': '色彩饱和:',
        'Brightness:': '明暗亮度:',
        'Reset': '归零',
        'Apply': '执行覆写',
        'Resize Canvas': '拓展画板天地',
        'Change Size': '指定绝对尺寸',
        '[w x h]': '[宽 x 高]',
        'Crop to closest valid generation size': '自动贴合到最优整除分辨率',
        'Shift Edges': '边缘外扩位移',
        'Resize': '调整尺寸',
        'Pressure Sensitivity': '开启手写板压感',
        'Round': '圆滑笔触',
        'Soft Round': '毛边柔和圆',
        'Square': '硬派方头',
        'Ctrl+Click on an image to set your settings to the ones used to generate it (except for any init image).': '秘籍：按住 Ctrl 单击历史美图，即可瞬间提取并应用它的所有生成参数！',
        'Decrisp': '消除过度锐化',
        'Auto': '智能切换',
        'High resolution samplers will automatically be used above a certain image size.': '突破一定尺寸阈值后，系统将自动挂载高分辨率专用采样器。',
        'Reduce artifacts caused by high prompt guidance values.': '抹平因 CFG(服从度) 拉得太高而导致的画面撕裂与过曝。',
        'Smea versions of samplers are modified to perform better at high resolutions.': '带有 SMEA 标识的采样器经过特殊调教，是攻克高分辨率细节崩溃的利器。',
        'SMEA Dyn variants of samplers are optimized to increase the coherence of higher resolution images without introducing the characteristic SMEA look. The effective range of resolutions is smaller than for regular SMEA.': 'SMEA Dyn 变体能在不引入传统涂抹感的前提下，硬核提升巨幅图像的结构连贯性。但其可驾驭的分辨率极值不如常规 SMEA。',
        'Legacy Prompt Conditioning Mode (Not Recommended)': '旧版提示词语义解析机制 (狗都不用)',
        'Stream Image Generation': '启用过程偷窥 (流式生成)',
        'Intermediates of generating images will be streamed.': '如拍立得显影一般，实时欣赏图片从马赛克走向清晰的全过程。',
        'Intermediates of generating images will not be streamed.': '蒙上双眼，等待进度条走完再迎接终极惊喜。',
        'Show Streamed Images Unprocessed': '无滤镜直播',
        'All streamed images will be shown unprocessed.': '直接将未做任何平滑处理的原始噪点演化暴露给您。',
        'In progress streamed images will be blurred and the first few steps will not be shown.': '为保护眼睛，过程图将进行高斯模糊，且略过最开始的混沌阶段。',
        'Image Format for Generated Images': '成品封装格式',
        'Automatic Download': '出图秒存本地',
        'Images will automatically download after generation.': '每当炼丹完成，图片都会自动弹窗保存到您的电脑里。',
        'Images will not automatically download after generation.': '我喜欢自己挑选，不要自动塞满我的硬盘。',
        'Hide Quickstart Gallery': '封印灵感画廊',
        'The quickstart gallery will be hidden on the image generation page.': '彻底隐藏底部的画廊，还您一个干净清爽的界面。',
        'The quickstart gallery will be shown on the image generation page.': '保留底部画廊，随时抄作业。',
        'Invalid': '判定无效',
        'Focused Area\nSelection': '局部焦点\n圈选',

        // --- 开局场景 ---
        'Storyteller': '纯文本创作',
        'Write alongside the AI to flesh out your writing and ideas.': '与 AI 携手，将您的灵感化为丰满的篇章。',
        'Celestial Curves': '凝视天体',
        'You are a wizened wizard of old. Comfortably seated in your most glorious of thrones, your eyes are focused on the curvature of the perfect object before you. This is your favorite past-time and your true purpose - to ponder. With a glazed stare, you watch and ponder what you see in the orb:': '你是一位古老而睿智的巫师。你惬意地深陷在至高无上的宝座中，双眼微眯，聚焦于面前那颗拥有完美曲率的球体。沉思，是你最爱的消遣，亦是你存在的真谛。透过浑浊却深邃的目光，你凝视着球体中倒映出的万千幻象：',
        'scenes of various natural settings from around the world, but also scenes of war and destruction. There are otherworldly scenes such as glowing orbs and strange beings and even representations of things that don\'t quite seem possible. The orb seems to change the more time you spend staring into it. As you ponder the many wondrous sights, you grow older and wearier each day. But there are always new wonders to be seen and marveled over. As you look deeper into the orb, you see new places in the distance and begin to wonder if perhaps this is truly another universe hidden beyond the stars. The orb itself seems to grow brighter as you ponder, and then dims slightly when you turn away to take a break. Each time you gaze at it, you feel the need to return to your throne and continue contemplating. Eventually the orb begins to glow bright again, and you must return to contemplate once more.': '这其中既有世间绮丽的风光，也不乏残酷的战火与文明的倾颓。更有散发着幽光的异界星体、扭曲的古怪生灵，乃至超越理智认知的不可名状之物。你凝视得越久，球体内的景象变换得愈发狂烈。在对这些奇观的日夜沉思中，你的躯壳逐渐衰老疲倦。但总有更新的奇迹在召唤着你的目光。当你将视线探入球体极深处时，远方未知之境若隐若现，令你甚至开始怀疑，在那群星的彼岸，是否真的蛰伏着另一个平行宇宙。随着你的思绪深入，球体愈发璀璨耀眼；当你转身小憩，它又体贴地暗淡下来。每一次移开目光，无形的引力都会拉扯你重返王座。终于，球体再次绽放出盛大光芒，命运在召唤，你必须再次沉入冥想。',
        'Text Adventure': '文字冒险游戏',
        'Begin an AI-generated quest using words and actions.': '敲下你的动作与台词，踏上一段完全由 AI 实时生成的未知道途。',
        'Army of what?!': '什么玩意儿的大军？！',
        'There are Corgies lined up as far as your eyes can see. Small Corgies, large Corgies, broad Corgies, skinny Corgies there even are Corgies riding upon other Corgies! They are all standing at attention, ready to do your bidding.': '放眼望去，成群结队的柯基犬一直绵延至地平线尽头。小巧的、巨大的、圆滚滚的、瘦骨嶙峋的……你甚至能看到有柯基像骑士一样骑在其他柯基背上！它们此刻正神气活现地列队立正，随时听候你的差遣。',
        'You look around for something to fight with.': '你慌乱地环顾四周，试图找件趁手的兵器。',
        'You have only two options: Walk or Fight. Which will you choose? The choice is clear; you need some way to defend yourself from these monstrous creatures. There\'s a good chance you\'ll end up fighting them anyway so it might as well be now.': '摆在面前的只有两条路：脚底抹油，或是正面硬刚。你的选择是？局势已经很明朗了，无论如何你都得想办法在这群毛茸茸的“怪物”面前保全性命。反正迟早免不了一战，不如现在就放手一搏！',
        'Choose a Scenario': '挑选开局剧本',
        'Generate Images': '直接生成图片',
        'Can\'t think of any ideas?': '脑子一片空白？',
        'Pick one of ours to get started.': '从官方精选剧本中挑一个爽玩吧。',
        'Use the browser below to select a scenario that tickles your fancy, you’ll be able to view the contents before starting.': '滑动下方卡片，找到那个最能撩拨你心弦的故事。放心，点开就能先预览剧情。',
        'Shuffle': '换一批剧本',
        'Loading...': '世界加载中...',
        'View All Scenarios': '浏览剧本大全',
        'Click Here': '猛击这里',
        'The Mysterious Note': '无名纸条疑云',
        'by': '作者:',
        'mystery': '悬疑',
        'detective': '侦探',
        'You are a private detective proud of your problem solving skills and the experience to back it up, but this latest case is your hardest one yet.': '你曾凭借出众的推理本能与老辣的江湖经验，在私家侦探界混得风生水起。但眼前这桩烫手的新案子，却成了你职业生涯中无法逾越的高墙。',

        // --- 故事控制面板 ---
        'Story': '故事核心',
        'Advanced': '极客微调',
        'Story Mode': '写作模式',
        'AI Model': '驱动引擎 (模型)',
        'Change Default': '更改默认',
        'Config Preset': '文本偏好预设',
        'Edit Preset': '调教预设',
        'Changes the settings of the AI model.': '在此调节发散度、惩罚等魔法参数。',
        'Default': '重置默认',
        'Memory': '长期记忆 (Memory)',
        'The AI will better remember info placed here.': '写在这里的设定会死死烙印在 AI 脑海里，贯穿整个故事。',
        'tokens': '词元',
        'Author\'s Note': '作者留言 (A/N)',
        'Info placed here will strongly influence AI output.': '此处的文字拥有极高的权重，能强行扭转 AI 的行文走向或语气。',
        'Lorebook Quick Access': '世界书快捷入口',
        'Story Options': '故事高阶选项',
        'View Story Stats': '查看万字成就统计',
        'Story is currently stored encrypted on the server.': '故事正以最高军事级加密安全躺在云端。',
        'Story is currently stored locally. Locally stored stories may be deleted by your browser after a period of non-use.': '故事仅留存在您的设备浏览器中。如果太久不碰，可能会被浏览器无情清理。',
        'Export Story': '导出保存',
        'To File': '存为文件',
        'Delete Story': '销毁当前故事',
        '(cannot be undone)': '(此操作不可逆转！)',
        'Delete': '残忍销毁',
        'Context': '上下文透视仪',
        'Get a full view of what’s sent to the AI.': '开启透视，赤裸裸地检视每次塞给 AI 的到底是什么数据。',
        'Last Context': '上一轮请求数据',
        'Current Context': '当前待发数据',
        'Edit System Prompt': '修改系统底层提示',
        'Extend NovelAI with custom scripts.': '通过植入自写代码，无限扩张你的 NovelAI 体验。',
        'Edit User Scripts': '进入代码控制台',
        'Logit Bias': '词汇概率干预 (Logit Bias)',
        'Weigh the AI’s chance of generating specific tokens.': '给特定词汇加减法码，强迫 AI 多说或闭嘴。',
        'Bias 0': '干预值 0',
        'empty': '空空如也',
        'Type in the area below, then press enter to save.': '在下方敲入你想干预的词，按下回车即可生效。',
        'Bias:': '干预力度：',
        'LESS': '绝口不提',
        'A bias of zero will have no effect.': '力度为 0 就是当无事发生。',
        'MORE': '挂在嘴边',
        'Tokens': '词元切分',
        'Click a token to edit it.': '点任意词块就能进行微调。',
        'Avoid Overused Words': '抑制陈词滥调',
        'Reduces the chance of generating words and phrases overused by AI models.': '给 AI 频繁爱用的“车轱辘话”套上枷锁，让用词更鲜活。',
        'Words will be chosen solely based on their natural likelihood of being generated.': '不加干预，任由 AI 根据自然概率随意吐字。',
        'Stop Sequences': '强制熔断符',
        'Duplicate and Start as Scenario': '以此为蓝本创建新剧本',
        'Imports current story as a scenario with placeholders': '把当前文章打包成填空模板，方便重开。',
        'Choose from a selection of generation settings.': '从琳琅满目的生成偏好中选个顺手的。',
        'Settings saved to story.': '参数已烙印进当前故事。',
        'Save to new Preset?': '要把它封装成全新的私人预设吗？',
        'Other Options': '其它功能',
        'Reset Changes': '撤销所有魔改',

        // --- 生成选项 ---
        'Generation Options': '生成控制中枢',
        'Randomness': '文本发散度 (Temperature)',
        'The higher the value, the more random the output!': '拉得越高，AI 越疯，但也越能写出神来之笔！',
        'Output Length': '单次出字长度',
        'Increase the length of the generated responses': '延长 AI 一口气能憋出多少个字',
        'Characters': '个字符',
        'Default: 1024': '默认：1024',
        'Advanced Options': '极客参数区',
        'Experimentation with these settings is encouraged, but be warned that their effects aren\'t always obvious.': '勇敢去折腾吧！不过别怪我没提醒，有些滑块拉了可能像没拉一样。',
        'This guide explains these settings.': '如果你一头雾水，就点这本秘籍看看。',
        'Sampling': '采样算法',
        'Top-K:': '候选截断 (Top-K):',
        'Default: 40': '默认：40',
        'Nucleus:': '核心采样 (Top-P):',
        'Default: 0.95': '默认：0.95',
        'Change Samplers': '重组算法流水线',
        '1 hidden': '已折叠 1 个',
        'Alternate Repetition Penalty': '平滑重复惩罚',
        'These options will strongly impact generation and are not recommended to set to high values.': '警告：这几个滑块极度危险！拉太高会导致 AI 逻辑崩坏，请克制。',
        'Presence:': '存在惩罚 (Presence):',
        '[0] (off)': '[0] (关闭)',
        'Default: 0 (off)': '默认：0 (关闭)',
        'Frequency:': '频率惩罚 (Frequency):',
        'Send': '发送请求',
        'Text is translated into tokens for the AI to understand. They are similar to syllables.': '文本会被切碎成“词元”，这就好比人类语言里的音节，AI 只认这个。',
        'Generate a random title for the story': '让 AI 灵光一闪，赐个标题',
        'Transform': '句式重构',
        'Expand': '注水扩写',
        'Condense': '提炼精简',
        'Rewrite Style': '风格重写',
        'Custom': '私人订制',
        'Make the text': '让这段文字变得',
        'kinda': '略微',
        'Adjust': '微调倾向',
        'a little': '稍微',
        'not much': '一点点',
        'quite a bit': '相当',
        'a lot': '非常',
        'very': '极其',
        'Rewrite to match the style.': '换个笔风，重新讲这段话。',
        'Context Management': '记忆中枢管理',
        'Enter a term': '搜索设定的词条...',
        'Enter a custom instruction.': '向 AI 下达私密指令...',
        'Search for an entry': '在浩瀚设定中搜索...',
        'Enabled': '火力全开',
        'Type here and hit enter to add a stop sequence': '键入特定符号按回车，AI 写到这就得乖乖停笔',
        'Enter the text you want to bias': '输入你想干预概率的字眼',
        'Because the AI only has so much Context it can see, remember not to give it too many details at once. Less can be more!': '由于 AI 一次能处理的上下文有限，请切记不要一次性塞入过多细节。留白亦是种美！',
        'option GLM 4.6, selected.': '已装载配置 GLM 4.6。',

        // --- 模型介绍 ---
        'Llama 3 Erato': 'Llama 3 Erato',
        'Our largest and most formidable, built with Meta Llama 3 70B.': '基于 Meta Llama 3 70B 锻造的超级引擎，智商碾压全场。',
        'Kayra': 'Kayra',
        'A fierce contender, now second best, crafted from the ground up.': '由我们团队从零开始手工搓出的强悍模型，实力稳居第二。',
        'Clio': 'Clio',
        'Our veteran powerhouse, still fast and reliable.': '久经考验的经典老将，主打一个稳准狠快。',
        'Euterpe': 'Euterpe',
        'A legacy model - use is no longer recommended.': '曾经的荣光，如今的古董——非念旧请勿使用。',
        'Krake': 'Krake',
        'Previously powerful, now legacy model - use is no longer recommended.': '昔日霸主，遗憾退役——不再推荐。',
        'Sigurd': 'Sigurd',
        'Genji': 'Genji (日文专精)',
        'A legacy Japanese language model - use is no longer recommended.': '旧时代的日文特化大模型——现在已经被淘汰了。',
        'Snek': 'Snek (代码专精)',
        'A legacy python code model - use is no longer recommended.': '过时的 Python 狂魔——请用更新的模型写代码。',

        // --- 世界书 (Lorebook) ---
        'Lorebook': '世界书设定集',
        'Entries': '全词条检索',
        'Manual': '查阅设定手册',
        'Entry': '词条本位',
        'Category': '分门别类',
        'Welcome to': '欢迎推开',
        'the Lorebook!': '世界书的大门！',
        'The perfect place to flesh out your story’s world, events, locations, characters, and environments. There are lots of settings, but you only need to worry about the Entry tab if you’re just getting started.': '这是您亲手构建世界观、编织历史事件、雕琢人物形象的无上圣地。先别管那些复杂的滑块，新手只需盯紧“词条本位”标签页即可。',
        'Simply place the info about your subject in the Entry Text field, and specify what Activation Keys should be looked for to show the entry to the AI.': '只需将设定文字塞进【条目内容】，并定好几个【触发关键词】。一旦故事里提到这几个词，这段设定就会像替身一样砸进 AI 的脑子里。',
        'You can get started by clicking the “+ Entry” button.': '别愣着了，点击左上角的“+ 词条”开始创造世界吧。',
        'Create an Entry': '新建一条设定',
        '0 Entries Selected': '当前未选中任何条目',
        'Select All': '全部勾选',
        'Negation': '逻辑取反 (不想看到什么)',
        'There\'s a fun phenomenon known as the \'pink elephant\' - try not to think about one, and it\'s there! AI works the same way, so try not to use words you don\'t want to see brought up.': '心理学中有一个有趣的“粉红大象”效应——你越努力不去想它，它反而越容易在脑海中浮现！AI 也有类似的机制，因此请尽量避免在设定中写入您不想看到的内容。',
        'New Lorebook Entry': '新建的世界书条目',
        'Entry has no keys.': '警告：此条目缺少灵魂(触发关键词)。',
        'Disabled': '已封印',
        'Advanced Conditions': '多重触发逻辑',
        'Entry Text': '条目正文',
        'Generator': '设定自动扩写器',
        'The following text will be referenced when the Keys are activated.': '当文中的字眼触碰了下方的关键词，AI 便会吸纳这里的文字。',
        '0 Tokens': '消耗 0 个词元',
        'Activation Keys': '触发关键词',
        'Activates the entry when found within the recent story.': '当这些词语出现在最近的故事剧情中，本设定立即生效。',
        'Always On': '常驻光环 (全局生效)',
        'No Keys set.': '空空如也，请设置关键词。',
        'No Category': '未归入任何门类',
        'Change Settings': '调整设定集参数',
        'Generation Type': '生成品类',
        'History': '时空记录',
        'Input Text': '引子 (给 AI 个起手式)',
        'Add Context (advanced)': '允许 AI 参考大背景',
        'Generate': '开始涌现',
        'Generation History': '设定生成履历',
        'New Category': '新建一本分类书',
        '0 entries': '这里空无一物',
        'Settings': '全局参数设定',
        'Lorebook Entry Header': '全局条目冠词',
        'The text entered here will be automatically placed above any entry in this category.': '写在这里的文字，会自动当成帽子，戴在属于本分类的所有条目正文头上。',
        'Add Condition': '添加触发条件',
        'No advanced conditions configured. Click \'Add Condition\' to create one.': '您还没有配置任何复杂判断逻辑。点“添加条件”开始整活。',
        'Note:': '温馨提示：',
        'Multiple top-level conditions use OR logic. The entry will activate if any condition evaluates to true.': '顶层条件之间是“或(OR)”的关系，随便中一个就能召唤该设定。',
        'True': '无脑触发',
        'Keyword Match': '匹配到指定词汇',
        'Lore Entry Active': '侦测到某条目已苏醒',
        'Random Chance': '掷骰子看脸概率',
        'Numeric Comparison': '比拼数值大小',
        'String Comparison': '核对文本是否一致',
        'AND Group': '必须同时满足',
        'OR Group': '满足一项即可',
        'NOT': '条件反转',
        'Always evaluates to true': '永远视为达成条件',
        'This is where you put what you want to be generated. Proper nouns like \'Geometry Incorporated\' or short descriptions like \'an enthusiastic merchant\' work best.': '这是提供生成源头的摇篮。塞点像“联合几何企业”这样的专有名词，或者“热情过头的黑商”之类的短语，效果拔群。',
        'You can add tags in parenthesis to further describe the entry, e.g. \'Stalagmal (prison, space)\'': '活用括号加标签，比如“阿卡姆 (疯人院, 哥谭)”能让 AI 秒懂。',
        'General': '万象包罗',
        'Person': '血肉之躯',
        'Place': '名胜古迹',
        'Thing': '奇珍异宝',
        'Life': '生态物种',
        'Faction': '割据势力',
        'Role': '职业身份',
        'Concept': '玄学概念',
        'Include Memory, Author\'s Note, the most recent story text (~2500 characters), or other Lorebook entries in context so that information can be used in generating entries.': '开启后，AI在扩写设定时，会偷看一眼您的长期记忆、作者留言以及最近的剧情上下文，确保生成的设定不突兀。',
        'Influences the generator towards generating a specific type of entry. A custom type can be set by typing with the dropdown open and hitting enter.': '用以约束 AI，让它乖乖按指定分类(如人物、地点)生成设定。您甚至可以在下拉框自己敲一个自定义类型。',
        'AI Prompting': '驯服 AI 的艺术',
        'Show and tell: provide the AI all kinds of prompts to get interesting results! Use everything from recipes to chat logs!': '大展身手：为 AI 提供五花八门的提示，收获意想不到的惊喜！不管是菜谱还是聊天记录，统统都能派上用场！',
        'Let the AI fill in the blanks for you! Choose the type of entry from the list, enter what you want to generate, and hit generate. You can also have the AI add to text written in the Lore entry just like in the Story.': '让 AI 替你脑洞大开！选好类别，丢个名词，敲击生成。你还可以像写小说一样，在设定框里写个开头让它续。',
        'Advanced conditions allow more complex logic for when this lore entry should activate.': '通过“高级条件”，你可以像写代码一样精准控制这条设定该在何时何地苏醒。',
        'The text here will be searched for Lorebook activation keys, and the matching Lore placed in context.': '只要故事文本碰到了这些关键词，对应的详尽设定就会瞬间涌入上下文。',
        'A Lorebook entry is activated and its text placed in context whenever one of its keys is found in the recent story. Keys are case-insensitive.': '世界书的唤醒机制很简单：剧情里提到了关键词，设定就生效。别担心，它不分大小写。',
        'Keys that begin and end with \'/\' are evaluated as regex. These regex keys are case-sensitive and support the following flags: i, s, m, and u.': '在首尾加上 \'/\' 即可唤醒正则表达式的狂暴力量。注意：正则严格区分大小写，且兼容 i, s, m, u 标志符。',
        'a recurring festival, Battle of Ryris (coup, demons)...': '比如：一场周期性的祭典，或者：莱瑞斯之战（政变，恶魔）...',
        'No advanced conditions configured. Click "Add Condition" to create one.': '还是一片荒芜。赶紧点“添加条件”开始构建逻辑判断吧。',
        'Prose': '长篇大论 (散文)',
        'Text that follows standard writing conventions is referred to as \'prose\'. The type of prose can vary—poetic stanzas, haikus, and so on. The AI will try to continue whatever you give it!': '符合标准写作规范的都算作“散文”。不管你给它喂十四行诗还是俳句，AI 都敢厚着脸皮往下接！',
        'Shows the last 50 outputs. Cleared on page refresh.': '仅保留您最近的 50 次脑洞。刷新页面后将化为泡影。',
        'Dock active tab to side': '将这个面板钉在侧边',
        'Enter Lorebook Keys to Search': '输入世界书关键词以大海捞针...',
        'Enter default entry header...': '设置一个全类通用的词条头部说明...',
        'Type information about the entry here.': '在此泼墨挥毫，书写设定的详情...',
        'Type a key here and hit enter to save it': '敲入触发词并按回车确认入库...',
        'This is where you put what you want to be generated. Proper nouns like "Geometry Incorporated" or short descriptions like "an enthusiastic merchant" work best.': '这是提供生成源头的摇篮。塞点像“联合几何企业”这样的专有名词，或者“热情过头的黑商”之类的短语，效果拔群。',
        'You can add tags in parenthesis to further describe the entry, e.g. "Stalagmal (prison, space)"': '活用括号加标签，比如“阿卡姆 (疯人院, 哥谭)”能让 AI 秒懂。',
        'History empty': '一片空白。',
        'always on': '全局常驻',
        'Press again to confirm deletion': '确认要痛下杀手吗？',
        'Perspective': '第一/二人称视角',
        'If a story is told from the author\'s perspective, it is first person. Second person is when \'you\' tell the story, and third person is telling you about other people. Try not to mix them up in the same story!': '别把视角搞乱了！第一人称是“我”，第二人称是“你”，第三人称是“他/她”。一旦在同个故事里频繁横跳，AI 会精神分裂的！',
        'No Entry selected.': '请先选定一个猎物。',
        'Select an Entry from the left to edit it.': '在左侧名录中点选一个词条开始调教。',
        'Delete Category?': '要摧毁整个分类吗？',
        'This cannot be reversed.': '世上没有后悔药。',
        'Delete Containing Entries': '连同子条目一并抹杀',
        'Deleting the category will also delete all entries within it.': '覆巢之下无完卵，该分类下的所有词条都将灰飞烟灭。',
        'Deleting the category will move all entries out of the category.': '仅仅是把这个书架砸了，里面的书会散落到“无分类”里。',
        'Delete it!': '动手吧！',
        'I changed my mind.': '我再想想。',
        'Tense': '时态连贯',
        'Remember to keep your tense consistent! Grammatically incorrect inputs might confuse the AI and produce lower quality outputs.': '请务必保持时态一致（如过去式/现在式）！满屏的病句只会让 AI 感到困惑，最终交给你一坨乱码。',
        'Unfinished Sentences': '开放式结尾的妙用',
        'Because the AI continues off the last thing, you can leave sentences unfinished for unexpected results. Try writing things like \'The man was\', to have the AI describe the subject.': 'AI 会顺着您的最后一句话往下写。您可以尝试留下半句话（比如“那个男人看起来”），让 AI 为您补全后续，收获意想不到的惊喜！',

        // --- 故事工具与导出 ---
        'As Scenario': '封装为互动剧本',
        'As Plaintext': '作为无格式文本',
        'To Clipboard': '一键拷入剪贴板',
        'As Image': '作为精美长图',
        'Delete Story?': '销毁整个故事？',
        'Saving...': '正在刻录数据...',
        'Story Statistics': '创作里程碑 (统计)',
        'Get a perspective on your writing.': '以数据的眼光，重温你在这篇故事上挥洒的汗水。',
        'Data': '核心数据',
        'Sections': '剧情段落',
        'Lorebook Entries': '世界书词条数',
        'Ephemeral Entries': '临时动态词条数',
        'Writing': '笔墨结晶',
        'User': '玩家心血',
        'AI': 'AI 代笔',
        'Edits': '精修次数',
        'Paragraphs': '分段',
        'Words': '总字数',
        'Sentences': '句子',
        'Generate Additional Stats': '挖掘更多隐藏成就',
        'Structure': '抉择树结构',
        'Current Step': '当前剧情步数',
        'Furthest Step': '最远推进步数',
        'Dead Ends': '走入死胡同的分支',
        'No Retry Streak': '一刀不改连击数',
        'Longest Abandoned Branch': '最长的废弃时间线',
        'Most Retries': '最卡文的重试次数',
        'Average Retries': '平均每步重试',
        'NaN': '未知',
        'Most Used Words': '你最爱用的词汇榜单',
        'WARNING: The following options are experimental and could result in permanent corruption of your story. Creating a backup first is heavily advised.': '红色警报：以下是可能导致时间线崩塌的高危实验操作。强烈建议动手前先备份存档。',
        'Trim Story': '修剪枝叶',
        'Flatten Story': '压路机模式 (扁平化)',
        'Reset to Prompt': '回到最初的起点',
        'Trim your Story?': '真的要修剪这棵故事树吗？',
        'Are you sure you want to trim the history of \'New Story\'?': '确认要清理这篇故事盘根错节的历史吗？',
        'This will delete all story branches.': '大清洗：除了当前这条时间线，其他所有未被选中的平行分支都会被彻底抹杀。',
        'Trim it!': '砍掉多余分支！',
        'Flatten your Story?': '准备好驾驶压路机了吗？',
        'Are you sure you want to flatten \'New Story\'?': '扁平化操作将把故事揉成一团。',
        'This will delete its entire history.': '这会让撤销列表彻底清空，只留下一纸最终文本。',
        'Flatten it!': '压扁它！',
        'Reset your Story to Prompt?': '将一切清零，回到提示词？',
        'Are you sure you want to reset \'New Story\' to its prompt?': '您正在试图倒转时间，回到这篇故事诞生前的那一刻。',
        'This will delete every input/output up to now.': '至今为止的所有玩家操作和 AI 生成将被抹除得一干二净。',
        'Reset it!': '按下重启按钮！',

        // --- 对话与杂项 ---
        'Dialogue': '对白与引号',
        'Remember to close off speech with quotation marks, or the AI may confuse when the dialogue is supposed to end! Similarly, specifying a speaker helps the AI stay on-track with who is saying what.': '切记：说出的话一定要用闭合的引号框起来！不然 AI 根本不知道人物什么时候闭嘴。另外，点名是谁说的，能有效防止 AI 搞错发言人。',
        'Excludes pronouns, conjunctions, prepositions, articles, and determiners': '算法已自动过滤掉无意义的代词、介词、连词和冠词。',
        'DO': '做动作',
        'SAY': '说台词',
        'What do you want to do?': '你打算采取什么行动？',
        'What do you want to say?': '你打算说些什么？',
        'Turn off Tips?': '嫌提示太烦？',
        'Are you sure you want to disable tips for this session?': '确定要在这轮会话里把下方的小贴士静音吗？',
        'You can re-enable or permanently turn off tips in the Interface Settings.': '别担心，您随时可以在界面设置里把它们喊回来，或是彻底判处死刑。',
        'Turn off Tips for this session': '就这次，让我清静清静',
        'Find in Story': '在故事里挖地三尺',
        'Token Probabilities': 'AI 选词的内心戏 (概率)',
        'Search Lorebook Entries': '搜寻那本布满灰尘的世界书',
        'Telepathy': '另类沟通 (比如心电感应)',
        'Want to talk non-verbally? That kind of communication can be defined with different <formatting> symbols rather than quotation marks.': '想要非传统的交流方式？丢掉引号吧！你可以用各种奇葩符号 <像这样> 来定义特殊的交流规则。',
        'Message Scaffolding & System Prompt': '消息骨架与系统预设指令',
        'tokens (': '词元 (',
        'Context Viewer': '上帝视角透视仪',
        'Previous Stage': '回溯上个阶段',
        'Next Stage': '推进下个阶段',
        'Show non-activated entries': '窥视那些沉睡的废案条目',
        'Stage': '所在阶段',
        'Order': '层级顺序',
        'Identifier': '代号标识符',
        'Inclusion': '是否卷入上下文',
        'Reason': '判定事由',
        'Reserved': '预留配额',
        'Trim Type': '被迫修剪的方式',
        'Included Phrase Bias Groups': '挂载的短语干预组',
        'Number of Included Phrase Bias Groups': '共计几个短语干预组',
        'Response:': 'AI 交出的答卷：',
        'Text': '原文内容',
        'Token IDs': '机器能懂的数字代码 (Token ID)',
        'Tokens:': '词元数：',
        'Characters:': '字符数：',
        'Building Context...': '正在为您构建记忆长城...',
        'The identifier for the context entry. Lorebook entries will use their display name.': '条目的身份标识。如果来自世界书，就会显示它的大名。',
        'Whether or not the entry was included in the context or not. A partially included entry is one that was trimmed.': '这块内容到底有没有被塞进送给 AI 的数据包里。如果是被腰斩的，就代表它遭到了修剪。',
        'The reason the entry was included or excluded from the context.': '为什么带它玩，或者为什么一脚踢开它的理由。',
        'If the entry was included because it was a Lorebook entry activated by a key the key will be shown here.': '如果是因为你触发了某个关键词而唤醒了这条设定，那个字眼就会曝光在这里。',
        'The number of tokens that were reserved by the entry.': '这条内容死皮赖脸占用的词元容量。',
        'The number of tokens that were used by the entry.': '它实际上耗费了多少词元容量。',
        'The total of this column may not be the same as the length of the resulting context.': '注意：这栏的数字全加起来，可能和最后发出去的总长度有出入。',
        'How the entry was trimmed to be able to fit it into the context.': '为了把大象装进冰箱，系统是怎么对这条内容动刀子的。',
        'The priority used when trimming is no trim > newline > sentence > token.': '动刀子的优先规则：能不剪就不剪 > 砍掉换行 > 砍掉句子 > 无情剁碎词元。',
        'Scene Change': '镜头切换与转场',
        'The dinkus (***) is used to tell the AI when to change scenes. You can also use an asterism (⁂) to tell it to start a whole new story!': '打出三个星号 (***) 就能暗示 AI：“该切镜头换场景了”。如果打出花型星群 (⁂)，更是直接掀桌子开启一个毫不相干的新故事！',
        'Just: Transformed context to message format.': '纯纯牛马：仅仅是把文字转成了系统能读懂的消息格式而已。',
        'not included': '被抛弃了 (未包含)',
        'no text': '空壳条目 (无文本)',
        'A/N': '作者留言 (A/N)',
        'included': '成功混入 (已包含)',
        'default': '原汁原味 (默认)',
        'As an Aside': '上帝的画外音',
        'You can use parentheses to give an aside in dialogue.': '在角色对话中，活用括号就能悄悄塞进去一段神机妙算的旁白。',
        'System Prompt': '深层系统指令',
        'The system prompt is the initial system message given to the model. Leave blank for the default system message.': '系统指令是注入到模型灵魂深处的第一句话。留空则沿用官方的稳妥套路。',
        'Reset to Default': '回归官方默认',
        'Copy Default': '偷渡一份默认指令',
        'Prefill': '强行预填充',
        'The prefill is inserted at the beginning of the most recent assistant message. Leave blank to use the default prefill.': '强行把这段话塞进 AI 回答的最前面。留空就用默认设定。',
        'The': '针对',

        // --- 杂项导航与交互说明 ---
        'menu.': '菜单注销。',
        'Previous': '回退',
        'Scenarios': '剧本库',
        'options.': '选项。',
        'Screenshot': '捕获唯美长图',
        'Settings.': '设置中调配。',
        'Credentials': '身份凭据',
        'Gift Keys': '兑换密钥仓库',
        'Logging Out': '正在撤离系统',
        'Changelogs': '更新编年史',
        'Capabilities': '性能指标',
        'AI Modules': '定制微调模块',
        'Account ID': '帐户唯一标识 ID',
        'Undo, Redo': '悔棋 (撤销)，反悔 (重做)',
        'Experiment!': '放肆去实验吧！',
        'Story Library': '浩瀚的故事库',
        'Color Coding': '文本着色体系',
        'Input, Output': '你写的，它编的',
        'Lorebook Keys': '世界书唤醒口令',
        'Text-to-Speech': '朗读引擎 (TTS)',
        'Text to Speech': '发音控制台',
        'Lorebook Export': '导出你的世界观',
        'Lorebook Import': '引入别人的世界',
        'Title Generation': '标题自动生成器',
        'AI Storytelling': '人机共创法则',
        'Repetition Penalty': '复读机惩罚机制',
        'Interface Settings': '界面定制面板',
        'Close this dialog': '关掉这个啰嗦的弹窗',
        'Manage Preferences': '偏好管理中心',
        'Lorebook Generation': '世界设定一键生成',
        'AI Output Quality': '驯化 AI 的输出质量',
        'Lorebook Generations': '全自动设定产出',
        'Perspective and Tense': '第一人称还是第三人称？',
        'Change Settings Order': '重新排列选项顺序',
        'Opens in a new window': '在新次元(窗口)中打开',
        'Repetition Penalty Range': '惩罚波及范围',
        'Repetition Penalty Slope': '惩罚衰减曲线',
        'Streamed Text-to-Speech': '高品质流式配音',
        'Opens an external website': '带您去外面的世界看看',
        'Lorebook Generation Type': '生成的设定类型',
        'Right Click Context Menu': '右键快捷施法菜单',
        'Lorebook Generation Types': '多维度的设定生成',
        'Lorebook Generation History': '设定生成的历史遗物',
        'Lorebook Generation Context': '生成设定时参考的背景',
        'Close Cookie Preferences': '保存并关闭 Cookie 设置',
        'Advanced - Lorebook Regex': '极客向 - 世界书正则匹配',
        'Advanced - Ephemeral Context': '极客向 - 临时动态上下文',
        'Streamed Text-to-Speech Seeds': '流式发音的声纹密码',
        'Speak Inputs, Outputs or both': '随心掌控朗读范围',
        'Dynamic Repetition Penalty Range': '动态自适应惩罚范围',
        'Advanced - Lorebook Generation Settings': '高阶 - 世界书生成参数',

        // --- 用户脚本管理 ---
        'New': '新加点料',
        'Account Scripts': '账户级霸道脚本',
        'loaded for all stories': '霸气侧漏，所有故事强制加载',
        'No Scripts': '此地空无一物',
        'Story Scripts': '故事级定制脚本',
        'loaded for this story': '仅为当前故事默默奉献',
        'Select a script, create a new one, or import one.': '请选择一个现有脚本，或是亲手搓一个、导入一个。',
        'Where do you want to add this script?': '你想把这段外星代码植入到哪里？',
        'To My Account': '注入我的账户灵魂',
        'Loaded for all stories.': '一次植入，全局所有故事生效。',
        'To This Story': '仅植入当前故事',
        'Loaded only for this story.': '仅在当前故事的环境中起作用。',
        'New User Script': '刚出炉的用户脚本',
        'Unknown': '薛定谔的状态',
        'Lock': '锁死防篡改',
        'Enable': '激活运行',
        'Info': '基础情报',
        'Code': '硬核代码',
        'Config': '可视化配置',
        'Permissions': '权限分配',
        'Storage': '存储空间',
        'Logs': '运行日志',
        'Diagnostics': '代码体检诊断',
        'This script is disabled. If you want to enable it, click on the dot next to the script name in the sidebar.': '这玩意儿被禁用了。想唤醒它，去侧边栏点一下它名字旁边的小圆点。',
        'Script Name': '脚本代号',
        'Description': '这是用来干嘛的？',
        'Memory Limit (MB, max 128)': '内存榨干上限 (MB, 顶峰 128)',
        'Script Information': '脚本底细',
        'Created:': '出厂日期:',
        'Last Updated:': '最后打磨:',
        'Script ID:': '唯一身份牌:',
        'Configuration Schema': '配置模式 (Schema) 定义',
        'Add Config': '加个新参数',
        'Configuration Values': '参数实录',
        'Save Config': '保存配置面板',
        'Reset to Defaults': '洗心革面，恢复默认',
        'No Configuration Defined': '开发者太懒，没定义任何界面',
        'Add configurations with the \'Add Config\' button above.': '点上面的“加个新参数”按钮自己整一个吧。',
        'RPG Formatting': 'RPG 游戏感排版',
        'Horizontal line (─), not to be confused with a dash, may be used for MMORPG-styled skills and statistics.': '全角水平线 (─) 并非普通破折号，它能完美模拟 MMORPG 游戏里的技能栏与属性面板排版。',
        'My Script': '我的心血结晶',
        'Are you sure you want to delete this script? This action cannot be undone.': '真要删？这代码一旦抹除，可是连渣都不剩的。',
        'Total': '综合汇总',
        'Diagnostics: New User Script': '全面体检: 您的新脚本',
        'Poetry and Lyrics': '吟游诗人的排版',
        'The em space ( ) is used on a newline when creating poetry or lyrics. Em space is different to the en space and the regular space and makes a big difference!': '在编写诗歌和歌词时，新行请使用全角空格 ( )。这和半角空格、普通空格有着天壤之别！',

        // --- 其他杂项与高级生成设置 ---
        'Set a bias on specific tokens to increase or decrease their chance of being generated. Surround with [square brackets] to input token ids (tokenizer specific). If a sequence of tokens is given, only the first will have the bias applied.': '给特定的词元施加影响，暗中提高或降低它诞生的概率。若要精准打击，可用 [方括号] 括住词元 ID。如果是塞进一长串话，只有开头的词会受干预。',
        'No Group Selected': '当前未点选任何词组',
        'Enable or disable this phrase group.': '决定这组短语干预的生杀大权。',
        'Cuts generation short upon reaching a specified string.': 'AI 只要吐出指定的这段字符，就会被立刻强行掐断生成。',
        'Quotations and Excerpts': '引经据典的排版',
        'Use an en space ( ) at the beginning of a newline to effectively mark it as a quotation or excerpt. This is different to both em space and the regular space!': '在新行开头敲一个半角空格 ( )，即可完美模拟文献摘录的格式！',
        'Keeps this many tokens, and deletes the rest.': '铁腕政策：只留下最靠前的一小撮候选词，剩下的通通枪毙。',
        'Adds the largest token probabilities until the sum reaches this value, then deletes the leftover tokens. Higher settings preserve more tokens.': '累加那些高概率的词，一旦概率总和达到你的阈值，排名靠后的词条就会被全部抛弃。数字越大，留下的词越五花八门。',
        'Samplers': '算法流水线',
        'You can reorder samplers here.': '你可以像叠积木一样重新排布各种算法的生效顺序。',
        'Disabled samplers will be hidden from the sidebar.': '被拉黑的采样器会从右侧的面板中完全消失。',
        'Temperature (Randomness)': '文本随机性 (Temperature)',
        'disable': '封印它',
        'Top-K Sampling': '候选截断 (Top-K)',
        'Nucleus Sampling': '核心提取 (Nucleus/Top-P)',
        'Min-P': '保底阈值 (Min-P)',
        '(disabled)': '(已封印)',
        'enable': '解除封印',
        'Applies a static penalty to the generation of tokens that appear within the Repetition Penalty Range.': '在指定的“惩罚范围”内，凡是敢重复露脸的词，统统课以固定重税。',
        'Applies a penalty to the generation of tokens based on the number of occurrences of that token within the Repetition Penalty Range.': '精准打击：一个词在“惩罚范围”内露脸次数越多，被扣的惩罚税就越高。',
        'World Constants': '世界常数与真理',
        'If your world has something specific about it, you can inform the AI of this distinction in your Lorebooks.': '如果你笔下的世界有某些打破常规的设定(如太阳是蓝的)，直接写进世界书，AI 就会奉为圭臬。',
        'Up to Date': 'AI 也紧跟潮流',
        'The AI is trained in some recent events, popular fiction and even celebrities. Specifics may need further prompting, but you should find it quite capable of broad strokes!': 'AI 也吃过现代互联网的瓜！它懂点最近的大事、热门网文甚至大明星。虽然细节上可能需要你稍作引导，但把控大方向绝对没问题。',
        'Bad Connection Story Conflicts': '网络波动引发的灵异冲突',
        'Story Backup': '未雨绸缪的备份',
        // --- 法律、隐私与安全提示 ---
        'By registering, you agree to consent to the NovelAI': '点击注册，即表示您已阅读并甘愿受 NovelAI',
        'Privacy Policy and Terms of Service': '隐私政策与霸王条款 (开玩笑的，是服务条款)',
        'apply.': '的约束。',
        'Terms of Service': '服务条款',
        'This site is protected by reCAPTCHA and the Google': '本网站由无情的 reCAPTCHA 把守，同时受 Google',
        'Privacy Policy': '隐私政策',
        'and': '以及',
        // --- 重要警告 (Note 部分) ---
        'Please take good care of your login credentials. Due to local encryption, losing your email or password results in permanently losing access to your remotely stored stories.': '极其严重警告：请把你的邮箱和密码死死锁进脑子里！由于采用本地加密技术，一旦忘记密码，云端的档案就成了永远解不开的死局。',
        'NOTE:': '重要提示：',
        'Encoding required. This will cost': '需要进行深度编码。这将在下次操作中吃掉你',
        'on the next generation.': '的代币。',

        // --- 首页界面 ---
        'Free!': '零元购！',
        'Pricing': '订阅方案',
        'Blog': '开发者博客',
        'Community': '玩家社区',
        'Login': '登 录',
        'Create High Quality': '触手可及的顶级',
        'AI Anime Art & Stories': 'AI 动漫插画与网文创作',
        'Start For Free Now': '即刻白嫖体验',
        'Unleash the power of AI with a suite of tools to easily bring your imagination to life without limits.': '利用一整套没有枷锁的 AI 工具，彻底释放潜能，让一切天马行空的想象化为现实。',
        'Start for': '马上',
        'Now': '开始',
        'Create Anime Art': '化身为大触画师',
        'Create Stories': '沉浸于小说连载',
        'Choose your adventure.': '你想先体验哪种魔法？',
        'Learn how NovelAI can enhance your creative potential.': '深挖 NovelAI 榨干你创作潜能的秘密。',
        'Writing Assistant': '你的贴身打字机',
        'Generate anime-inspired characters.': '信手捏出令人疯狂的纸片人老婆/老公。',
        'Without limits.': '去他的审查与限制。',
        'Play with your own imagination using an interface tailored towards making generating imagery simple and fast.': '专为“出图如饮水”打造的极简界面，不让繁琐的操作束缚住你脱缰的想象力。',
        'Features': '核心超能力',
        'Purpose-built Creative Editor': '专为创造力而生的画板',
        'Centered around creativity, NovelAI’s Image Generation UI keeps you focused on the thing that matters most, your images.': 'NovelAI 的界面设计做尽了减法，只为让你沉浸在最重要的事情上——你的旷世杰作。',
        'Reliable Image Adjustment': '指哪打哪的后期工具',
        'Use Image2Image to change details while following the original composition, or Enhance it to increase the level of detail in the image.': '利用图生图在保持原构图的基础上大刀阔斧，或是使用“细节提升”让画面逼真到每个像素。',
        'Random Prompt': '掷出命运的骰子',
        'Out of ideas? Click the dice button and get brand new inspiration without any work on your end required.': '大脑宕机了？猛击骰子图标，不用你动一根手指，绝赞的灵感自动送上门。',
        'Advanced AI Settings': '供极客把玩的硬核参数',
        'When the defaults don’t quite tickle your fancy, fiddle and experiment with a variety of samplers and options.': '如果默认出图没内味儿，一堆硬核的采样器和滑块正在后台等你尽情调教。',
        'A collection of tools built to make generating fun and easy.': '一切工具的堆砌，只为让炼丹变得如同游戏般充满乐趣。',
        'Create predictable results with high variety, effortlessly.': '轻松打破“抽卡盲盒”魔咒，在保持超高画面多样性的同时，死死拿捏住你想要的细节。',
        'Don’t settle for randomness, outline all the best parts of your character using natural language, or a comprehensive set of visual tags.': '别向随机性妥协！无论是优雅的自然语言，还是堆砌成山的视觉标签，都能将你笔下角色的每一寸肌肤勾勒得淋漓尽致。',
        'PROMPT': '给 AI 的咒语',
        'Outline each character distinctly, without missing any details.': '绝不放过任何一丝细节，精准狙击每个角色的特征。',
        'Utilize multiple character prompts to design each separate character in your image, for more control over your composition.': '借助极其强大的“多角色提示词”系统，让你能够像导演一样，为同框的每一个角色量身定制外观。',
        'CHAR 1 PROMPT': '1 号演员剧本',
        'CHAR 2 PROMPT': '2 号演员剧本',
        'Transfer the aesthetics from your favorite generations to new ones.': '把绝美画作的神韵，一滴不漏地转移到下一张图里。',
        'Vibe Transfer pulls the best parts out of an image and uses it as direct visual inspiration for new generations.': '“风格提取”能榨取一幅画中最能打动人心的美学特质，并将其化作直接的视觉养分，哺育新的创作。',
        'Learn more about Vibe Transfer': '深入了解“风格提取”黑科技',
        'Naturally correct mistakes, or create brand new details.': '擦除画崩的残次品，或是凭空捏造全新的细节。',
        'Inpaint your image with a brush to fix any errors, or prompt for something different to shake things up.': '拿起画笔，在需要修改的地方轻轻一抹，无论是修复断掉的六根手指，还是强行给美少女加上猫耳，都易如反掌。',
        'Put the final touches on your images before sharing them with the world.': '在把你的大作发到网上装杯之前，先来个画龙点睛的微调。',
        'Turn creations into something new, or adjust a generation for use somewhere else.': '榨干旧图的剩余价值，改头换面成为全新的惊艳素材。',
        'Join thousands of AI artists that use NovelAI every single day.': '加入由全球数以万计顶尖 AI 炼丹师组成的狂热军团。',
        'Start with a free trial.': '先别掏钱，白嫖试试。',
        '30 Free\nGenerations': '白嫖 30 次\n精美画作',
        'Up to 1024x1024\nresolution': '最高解禁 1024x1024\n高清画质',
        'Start for Free': '零成本开玩',
        'What kind of creator are you?': '阁下是何方神圣？',
        'Compare and pick the right plan for you.': '货比三家，挑个最配你的套餐。',
        'Writer': '文字巨匠',
        'AI Artist': '视觉艺术家',
        'Both': '我全都要！',
        'Explore\nOur Plans': '深入探秘\n所有套餐',
        '/mo': '/月',
        'USD': '刀 (USD)',
        'Unlimited Images': '无限畅炼图',
        'Image Gen Access': '图像生成特权',
        'Access to our image generation features.': '为你敞开通往二次元视觉盛宴的大门。',
        'Pay As You Go': '随用随买 (点卡)',
        'Unlimited*': '不限量爆肝*',
        'Purchase Discount': '氪金打骨折',
        'The amount taken off our on-demand Anlas pricing.': '在你额外购买代币时，享受这实打实的折扣比例。',
        '20% Discount': '全场 8 折',
        'Bonus': '月卡福利金',
        'Free extra monthly currency for use in generating images on NovelAI.**': '每个月白送你的代币池，专供你尽情挥霍出图。**',
        'OR': '或者',
        'Not interested in a monthly subscription?\nCheck out our pay-as-you go options instead.': '不想被月供绑架？\n试试我们的点卡制，用多少充多少。',
        '* For images of up to 1024x1024 pixels and up to 28 steps when generating a single image.': '* “无限畅炼图”特权有小前提：单张出图分辨率不能超过 1024x1024，且迭代步数不得高于 28。超过就得扣代币了。',
        'A text editor built to let AI write': '这是一个理念完全不同的文本编辑器，',
        'with': 'AI 只是陪你',
        'you, not': '共同创作的僚机，而绝不是',
        'for': '替你',
        'you.': '流水线代工的机器。',
        'A writing workspace should feel like home. We give you the freedom to customize and get comfortable.': '写作的工位必须舒服得像家里一样。我们把所有外观权限都交给你，只求你用的顺心。',
        'Customizable Workspace': '深度定制你的赛博书桌',
        'Have fun with a flurry of visual customizations like colors and fonts. Our editor is accessibility-friendly with shortcuts, screen reader compatibility and options for those with dyslexia or vision impairment.': '沉醉在颜色和字体的无穷搭配中吧！我们的编辑器还对残障人士拉满了关怀——满血快捷键、屏幕阅读器兼容，乃至专为阅读障碍或视力受损者打造的贴心模式，一应俱全。',
        'Stay Organized': '拒绝杂乱无章',
        'Place your finest stories into separate shelves for faster discovery and cleaner organization.': '把你的心血之作分门别类塞进不同书架，找起来快如闪电，看着也赏心悦目。',
        'AI Generation Presets': '无脑套用的生成偏好',
        'No need to fiddle with sliders and knobs, just find a preset that works the best for your situation.': '没心思去研究那些像飞机仪表盘一样的参数滑块？直接选个预设，即插即用。',
        'AI Memory': '给 AI 植入脑机芯片',
        'At any point, insert things you’d like the AI to remember or influence how the AI should write.': '在任何时候，强行将你需要牢记的设定塞进 AI 的记忆中枢，直接接管它的行文逻辑。',
        'Take advantage of everything an AI cowriter has to offer.': '疯狂压榨这位不知疲倦的 AI 共同作者。',
        'Feel stuck? Automagically continue the parts you’re struggling to write.': '卡文卡到想撞墙？让魔法为你续写那些绞尽脑汁也憋不出的段落。',
        'At any point in the writing process, let our AI decide the next best steps for your story. Outputs match your writing style and move things forward when you’re stuck.': '不管推进到哪一步，只要你犯了难，直接把笔丢给 AI 让他决定剧情走向。它甚至能惟妙惟肖地模仿你的文风，强行打破僵局。',
        'A Malevolent Beast Abound': '夜黑风高恶兽出没',
        'You already know your world, make sure the AI knows it too.': '你是造物主，但你得确保 AI 也懂你的规矩。',
        'At any point, build your Lorebook up with important story elements, characters, items, and locations, so our AI knows exactly how to help write your story.': '随时在你的“世界设定集”中堆砌那些重要的人物、神兵利器和名胜古迹，一旦建立，AI 就能分毫不差地辅佐你编织故事。',
        'Dive into a web of probability and pick out new directions.': '潜入庞大的概率网络，手动挑选剧情的裂变分支。',
        'With Token Probabilities, pull back the curtain and see what the AI': '揭开“词元概率”这块遮羞布，看看 AI 脑子里',
        'ORIGINAL': '默认生成',
        'NEW PATH': '你手动挑选的全新分支',
        'Join thousands of writers that use NovelAI every single day.': '加入成千上万名每天沉浸在 NovelAI 敲字的狂热作家行列。',
        '50 Free\nGenerations': '白送 50 次\n文字续写',
        '8,182 tokens of Memory': '8,182 词元的上下文容量',
        '~32,768 characters': '脑容量约等同 32,768 个字符',
        'Unlimited Text Generations': '文字生成毫无上限',
        'Generate as many stories as you want without usage caps.': '无论你写出多恢弘的史诗，我们绝不踩刹车，文本生成随便用。',
        'Memory Size': '大脑极值容量',
        '(Characters)': '(估算字符)',
        'The number of characters the AI can remember. (1 Token = ~4 Characters)': 'AI 能够一口气记住的上下文剧情极限。（1 词元 ≈ 4 个英文字符）',
        'Advanced and fast AI TTS built to read your written stories out aloud.': '搭载快如闪电的高品质 AI 语音引擎，能极富感情地朗读你的故事大作。',
        'Our best SOTA model for cowriting.': '业界顶尖 (SOTA)，我们用来辅助写作的绝对主宰模型。',
        'Our latest text gen model, now with 4x context.': '新鲜出炉的续写模型，这次我们把它的记忆力硬生生拔高了 4 倍。',
        '30 Free Image\nGenerations': '白送 30 张\n精美画作',
        '50 Free Text\nGenerations': '白送 50 次\n文字续写',
        '** A pool of Anlas that refills each month to the amount for your subscription tier. It will only refill if you have less than the amount for your subscription tier.': '** 这是你的月卡福利金库。每个月会自动补满到对应套餐的额度（前提是你把它挥霍到低于上限了，存不下来的）。',
        'Our Latest Blog Posts': '来自官方的锐评与博文',
        'For the Casual': '致佛系创作者',
        'For the Professional': '致硬核炼丹师',
        'For the Enthusiast': '致狂热发烧友',
        'Contact Us': '向我们反馈',
        'Press Kit': '媒体新闻包',
        'Updates': '功能迭代时间线',
    };

    // ==========================================
    // 3. 动态正则匹配
    // ==========================================
    const regexI18n = [
        { regex: /^Are you sure you want to delete "(.*?)"\?$/, replacement: '确定要删除 "$1" 吗？' },
        { regex: /^Are you sure you want to delete '(.*?)'\?$/, replacement: '确定要删除 "$1" 吗？' },
        { regex: /^Are you sure you want to delete the category "(.*?)"\?$/, replacement: '确定要摧毁整个 "$1" 分类吗？' },
        { regex: /^Are you sure you want to delete the category '(.*?)'\?$/, replacement: '确定要摧毁整个 "$1" 分类吗？' },
        { regex: /^Are you sure you want to trim the history of "(.*?)"\?$/, replacement: '确定要抹除 "$1" 的平行分支吗？' },
        { regex: /^Are you sure you want to trim the history of '(.*?)'\?$/, replacement: '确定要抹除 "$1" 的平行分支吗？' },
        { regex: /^Are you sure you want to flatten "(.*?)"\?$/, replacement: '确定要用压路机把 "$1" 压成单线文本吗？' },
        { regex: /^Are you sure you want to flatten '(.*?)'\?$/, replacement: '确定要用压路机把 "$1" 压成单线文本吗？' },
        { regex: /^Are you sure you want to reset "(.*?)" to its prompt\?$/, replacement: '确定要将 "$1" 一把火烧回到最初的提示词状态吗？' },
        { regex: /^Are you sure you want to reset '(.*?)' to its prompt\?$/, replacement: '确定要将 "$1" 一把火烧回到最初的提示词状态吗？' },
        { regex: /^(\d+\/\d+) text generations remaining\.$/, replacement: '文本额度剩余 $1 次。' },
        { regex: /^Context: (\d+) tokens \(max tokens \[(\d+)\] - output length \[(\d+)\] - continue to sentence end allowance \[(\d+)\]\)$/, replacement: '上下文: $1 词元 (上限 [$2] - 输出长 [$3] - 句尾补全余量 [$4])' },
        { regex: /^max tokens \[(\d+)\] - output length \[(\d+)\] - continue to sentence end allowance \[(\d+)\]$/, replacement: '词元上限 [$1] - 输出长 [$2] - 句尾补全余量 [$3]' },
        { regex: /^option (.*?), selected\.$/, replacement: "已为您装载选项 $1。" },
        { regex: /^You are currently focused on option (.*?) Select a (.*?) is focused , press Down to open the menu,$/, replacement: "当前正在关注 $1。按向下箭头可展开详细菜单。" },
        { regex: /^You are currently focused on option (.*?) (\d+) results available\.(.*)$/, replacement: "聚焦于 $1，共发现 $2 个结果。" },
        { regex: /^This prompt is using (\d+) of the currently used (\d+) tokens\. Max total tokens: (\d+)$/, replacement: "当前提示词消耗 $1 词元 (当前总量 $2 词元)。极限容量: $3 词元" },
        { regex: /^(\d+) tokens out of (\d+) tokens used$/, replacement: "已挤占 $1 / $2 词元" },
        { regex: /^Strength (.*)$/, replacement: "重绘幅度 $1" },
        { regex: /^Noise (.*)$/, replacement: "噪点注入 $1" },
        { regex: /^Set Character (\d+)’s Position$/, replacement: "调整 $1 号角色的绝对坐标" },
        { regex: /^Character (\d+)$/, replacement: "$1 号角色" },
        { regex: /^(\d+\/\d+) image generations remaining\.$/, replacement: '画作额度剩余 $1 张。' }
    ];

    // ==========================================
    // 4. 翻译引擎
    // ==========================================

    // 严禁进入的标签，不仅彻底略过代码编辑器、样式表、原生富文本框，还避开 SVG 避免破坏图形内容
    const ignoreTags = new Set(['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEXTAREA', 'CODE', 'SVG', 'PATH']);
    // NovelAI中经常高频变动的核心打字区域
    const editorSelectors = '.ProseMirror, [contenteditable="true"], .CodeMirror';

    // 基础判定：检查元素是否属于被忽略的范畴
    function isIgnored(node) {
        if (!node) return true;
        let el = node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement;
        if (!el) return true;
        if (ignoreTags.has(el.tagName)) return true;
        if (el.isContentEditable || (el.closest && el.closest(editorSelectors))) return true;
        return false;
    }

    // 执行纯文本翻译逻辑
    function translateTextNode(node) {
        let originalText = node.nodeValue;
        if (!originalText) return;
        
        let trimmedText = originalText.trim();
        if (!trimmedText) return; // 跳过空白节点，极大节省开销

        // 优先字典全词精确匹配
        let exactMatch = i18n[trimmedText];
        if (exactMatch) {
            let newText = originalText.replace(trimmedText, exactMatch);
            if (originalText !== newText) { 
                node.nodeValue = newText;
            }
            return;
        }

        // 仅在存在数字、符号特征时，才降级走低效率的正则是替换引擎
        for (let i = 0; i < regexI18n.length; i++) {
            let item = regexI18n[i];
            if (item.regex.test(trimmedText)) {
                let replaced = trimmedText.replace(item.regex, item.replacement);
                if (trimmedText !== replaced) {
                    node.nodeValue = originalText.replace(trimmedText, replaced);
                }
                return;
            }
        }
    }

    // 翻译元素属性
    function translateAttributes(el) {
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
            let placeholder = el.getAttribute('placeholder');
            if (placeholder && i18n[placeholder.trim()]) {
                el.setAttribute('placeholder', i18n[placeholder.trim()]);
            }
        }
        if (el.hasAttribute('title')) {
            let title = el.getAttribute('title');
            if (title && i18n[title.trim()]) {
                el.setAttribute('title', i18n[title.trim()]);
            }
        }
        if (el.tagName === 'INPUT' && (el.type === 'submit' || el.type === 'button') && el.value) {
            let trimmedVal = el.value.trim();
            if (trimmedVal.toLowerCase() === 'submit') {
                el.value = '提 交';
            } else if (i18n[trimmedVal]) {
                el.value = i18n[trimmedVal];
            }
        }
    }

    // TreeWalker 过滤器：原生 C++ 级别跳过不需要翻译的 DOM 分支
    const treeWalkerFilter = {
        acceptNode: function(node) {
            let el = node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement;
            if (!el) return NodeFilter.FILTER_SKIP;
            
            // 碰到编辑器层(ProseMirror)等，直接 FILTER_REJECT
            // 此时不仅自身被跳过，其内部【所有子孙节点】均被剪枝
            if (ignoreTags.has(el.tagName) || el.isContentEditable || (el.closest && el.closest(editorSelectors))) {
                return NodeFilter.FILTER_REJECT;
            }
            return NodeFilter.FILTER_ACCEPT;
        }
    };

    // 使用高效率的原生 TreeWalker 深入遍历并翻译
    function processTree(root) {
        let rootEl = root.nodeType === Node.ELEMENT_NODE ? root : root.parentElement;
        if (rootEl && (ignoreTags.has(rootEl.tagName) || rootEl.isContentEditable || rootEl.closest(editorSelectors))) {
            return; // 树根即为毒区，直接剪断
        }

        if (root.nodeType === Node.TEXT_NODE) {
            translateTextNode(root);
            return;
        } else if (root.nodeType === Node.ELEMENT_NODE) {
            translateAttributes(root);
        }

        // 构建原生迭代器
        const walker = document.createTreeWalker(
            root, 
            NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT, 
            treeWalkerFilter, 
            false
        );
        
        let currentNode;
        while (currentNode = walker.nextNode()) {
            if (currentNode.nodeType === Node.TEXT_NODE) {
                translateTextNode(currentNode);
            } else if (currentNode.nodeType === Node.ELEMENT_NODE) {
                translateAttributes(currentNode);
            }
        }
    }


    // ==========================================
    // 5. DOM 变动监听器与平滑防抖 (节流)
    // ==========================================
    let pendingMutations = new Set();
    let debounceTimer = null;

    const observer = new MutationObserver((mutations) => {
        let hasValidMutations = false;

        for (let i = 0; i < mutations.length; i++) {
            let m = mutations[i];
            let target = m.target;
            
            // 在产生 Mutation 的瞬间直接剔除富文本编辑器打字事件
            let el = target.nodeType === Node.ELEMENT_NODE ? target : target.parentElement;
            if (el && (ignoreTags.has(el.tagName) || el.isContentEditable || el.closest(editorSelectors))) {
                continue; 
            }

            pendingMutations.add(m);
            hasValidMutations = true;
        }

        // 核心优化：防抖(Debounce)。
        // 使用 setTimeout (约50ms) 能保证主线程不会因为高频 DOM 更新而锁死
        if (hasValidMutations) {
            if (debounceTimer) clearTimeout(debounceTimer);
            debounceTimer = setTimeout(processMutations, 50);
        }
    });

    function processMutations() {
        observer.disconnect(); // 切断监听器，避免脚本自身修改引发死循环海啸
        
        let mutationsToProcess = Array.from(pendingMutations);
        pendingMutations.clear();
        let processedNodes = new Set(); // 记录本次轮回的熟面孔，防重

        for (let m of mutationsToProcess) {
            if (m.type === 'childList') {
                for (let node of m.addedNodes) {
                    if (processedNodes.has(node)) continue;
                    processTree(node); 
                    processedNodes.add(node);
                }
            } else if (m.type === 'characterData') {
                if (processedNodes.has(m.target)) continue;
                if (!isIgnored(m.target)) {
                    translateTextNode(m.target);
                }
                processedNodes.add(m.target);
            } else if (m.type === 'attributes') {
                if (processedNodes.has(m.target)) continue;
                if (!isIgnored(m.target)) {
                    translateAttributes(m.target);
                }
                processedNodes.add(m.target);
            }
        }

        observe(); // 翻译完毕，重新拉起监听网
    }

    function observe() {
        observer.observe(document.body, {
            childList: true,
            subtree: true,
            characterData: true,
            attributes: true,
            attributeFilter: ['placeholder', 'title', 'value']
        });
    }

    // 脚本启动时，全页执行一次快速遍历大清洗
    processTree(document.body);
    observe();

})();
